.\"     Title: amaespipe
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 08/22/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "AMAESPIPE" "8" "08/22/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
amaespipe - wrapper program for aespipe
.SH "SYNOPSIS"
.HP 10
\fBamaespipe\fR
.SH "DESCRIPTION"
.PP

\fBamaespipe\fR
requires
\fBaespipe\fR,
\fBuuencode\fR
and
\fBgpg\fR
to work\. Aespipe is available from
: http://loop-aes.sourceforge.net
.PP

\fBamaespipe\fR
will search for the aespipe program in the following directories: /usr/bin:/usr/local/bin:/sbin:/usr/sbin\.
.PP

\fBamaespipe\fR
is called by
\fBamcrypt\fR
for
\fIAmanda\fR
data encryption\.
.PP

\fBamaespipe\fR
is based on aespipe\'s bzaespipe program\. It calls aespipe to encrypt data using AES256 as the encryption and SHA256 as the hash function\. GPG key should be stored in $AMANDA_HOME/\.gnupg/am_key\.gpg\.
\fBamaespipe\fR
reads passphrase from file descriptor 3\. During decryption,
\fBamaespipe\fR
autodects encryption type and hash function from the encrypted image\.
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamanda.conf\fR(5),
\fBaespipe\fR(1),
\fBamcrypt\fR(8),
\fBgpg\fR(1),
: http://wiki.zmanda.com
