'\" t
.\"     Title: amanda.conf
.\"    Author: James da Silva <jds@amanda.org>
.\" Generator: DocBook XSL Stylesheets vsnapshot_8273 <http://docbook.sf.net/>
.\"      Date: 11/05/2009
.\"    Manual: File formats and conventions
.\"    Source: Amanda 2.6.1p2
.\"  Language: English
.\"
.TH "AMANDA\&.CONF" "5" "11/05/2009" "Amanda 2\&.6\&.1p2" "File formats and conventions"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amanda.conf \- Main configuration file for \fIAmanda\fR, the Advanced Maryland Automatic Network Disk Archiver
.SH "DESCRIPTION"
.PP
\fBamanda.conf\fR(5)
is the main configuration file for
\fIAmanda\fR\&. This manpage lists the relevant sections and parameters of this file for quick reference\&.
.PP
The file
\fB<CONFIG_DIR>/<config>/amanda\&.conf\fR
is loaded\&.
.SH "SYNTAX"
.PP
There are a number of configuration parameters that control the behavior of the
\fIAmanda\fR
programs\&. All have default values, so you need not specify the parameter in
\fBamanda\&.conf\fR
if the default is suitable\&.
.SS "COMMENTS"
.PP
Lines starting with # are ignored, as are blank lines\&. Comments may be placed on a line with a directive by starting the comment with a #\&. The remainder of the line is ignored\&.
.SS "KEYWORDS AND IDENTIFIERS"
.PP
Keywords are case insensitive, i\&.e\&.
\fBmailto\fR
and
\fBMailTo\fR
are treated the same\&. Also, the characters
\fB\'\-\'\fR
and
\fB\'_\'\fR
are interchangeable in all predefined
\fIAmanda\fR
keywords:
\fBdevice_property\fR
and
\fBdevice\-property\fR
have the same meaning\&.
.PP
Identifiers are names which are defined in the configuration itself, such as dumptypes or interfaces\&. Identifiers are are case\-insensitive, but sensitive to
\fB\'\-\'\fR
vs\&.
\fB\'_\'\fR\&. Identifiers should be quoted in the configuration file, although For historical reasons, the quotes are optional\&.
.PP
Strings are always quoted with double quotes ("), and any double quotes or backslashes within the string are escaped with a backslash:
.sp
.nf
tapelist "/path/to/tapelist"
property "escaped\-string" "escaping: \e\e (backslash) and \e" (double\-quote)"
.fi
.PP
To summarize, then:
.sp
.nf
                          # QUOTES        CASE            \-/_
logdir "logs"             # required      sensitive       sensitive
send\-amreport\-on strange  # prohibited    insensitive     insensitive
tapetype "EXABYTE"        # optional      insensitive     sensitive

define dumptype "dt" {    # optional      insensitive     sensitive
  "dumptype\-common"       # optional      insensitive     sensitive
  strategy noincr         # prohibited    insensitive     insensitive
}
.fi
.SS "VALUE SUFFIXES"
.PP
Integer arguments may have one of the following (case insensitive) suffixes, some of which have a multiplier effect:
.PP
\fBb byte bytes\fR
.RS 4
Some number of bytes\&.
.RE
.PP
\fBbps\fR
.RS 4
Some number of bytes per second\&.
.RE
.PP
\fBk kb kbyte kbytes kilobyte kilobytes\fR
.RS 4
Some number of kilobytes (bytes*1024)\&.
.RE
.PP
\fBkps kbps\fR
.RS 4
Some number of kilobytes per second (bytes*1024)\&.
.sp
It is the default multiplier for all size options\&.
.RE
.PP
\fBm mb meg mbyte mbytes megabyte megabytes\fR
.RS 4
Some number of megabytes (bytes*1024*1024)\&.
.RE
.PP
\fBmps mbps\fR
.RS 4
Some number of megabytes per second (bytes*1024*1024)\&.
.RE
.PP
\fBg gb gbyte gbytes gigabyte gigabytes\fR
.RS 4
Some number of gigabytes (bytes*1024*1024*1024)\&.
.RE
.PP
\fBtape tapes\fR
.RS 4
Some number of tapes\&.
.RE
.PP
\fBday days\fR
.RS 4
Some number of days\&.
.RE
.PP
\fBweek weeks\fR
.RS 4
Some number of weeks (days*7)\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
The value
\fBinf\fR
may be used in most places where an integer is expected to mean an infinite amount\&.
.sp
Boolean arguments may have any of the values
\fBy\fR,
\fByes\fR,
\fBt\fR,
\fBtrue\fR
or
\fBon\fR
to indicate a true state, or
\fBn\fR,
\fBno\fR,
\fBf\fR,
\fBfalse\fR
or
\fBoff\fR
to indicate a false state\&. If no argument is given,
\fBtrue\fR
is assumed\&.
.sp .5v
.RE
.RE
.SS "PARAMETER ORDER"
.PP
In general, the order in which parameters occur in the configuration file does not matter, with the exception of subsection inheritance\&. For example, if dumptype "normal\-encrypt" which inherits from dumptype "normal", then "normal" must appear first in the configuration file\&.
.SS "STRINGS"
.PP
Quoted strings in Amanda follow a common, C\-like syntax\&. Printable characters and whitespace are kept as\-is, except that the backslash character (\e) is used as an escape character, and a double\-quote ends the string\&. The allowed escape sequences are
.sp
.nf
    ESCAPE SEQUENCE     BECOMES
    \e\e                  \e
    \e"                  "
    \en                  (newline)
    \et                  (tab)
    \er                  (carriage return)
    \ef                  (form\-feed)
    \e1 \- \e7
    \e01 \- \e77
    \e001 \- \e377         (character specified in octal)
.fi
Illegally quoted strings are handled on a "best\-effort" basis, which may lead to unexpected results\&.
.PP
Examples:
.sp
.nf
finserver "/data/finance/XYZ Corp\'s \e"real\e" finances" finance\-high eth0 \-1
property "syspath" "C:\e\eWINDOWS\e\eSYSTEM"
.fi
.SH "GLOBAL PARAMETERS"
.PP
\fBorg\fR \fI string\fR
.RS 4
Default:
\fIdaily\fR\&. A descriptive name for the configuration\&. This string appears in the Subject line of mail reports\&. Each
\fIAmanda\fR
configuration should have a different string to keep mail reports distinct\&.
.RE
.PP
\fBmailer\fR \fI string\fR
.RS 4
Default found by configure\&. A mail program that can send mail with \'\fIMAILER \-s "subject" user < message_file\fR\'\&.
.RE
.PP
\fBmailto\fR \fI string\fR
.RS 4
Default:
\fIoperators\fR\&. A space separated list of recipients for mail reports\&.
.RE
.PP
\fBsend\-amreport\-on\fR [all|strange|error|never]
.RS 4
Default:
\fBall\fR\&. Specify which types of messages will trigger an email from amreport\&. amreport is used by amdump and amflush\&.
.PP
\fBall\fR
.RS 4
Send an email on any message\&.
.RE
.PP
\fBstrange\fR
.RS 4
Send an email on strange or error message\&. A strange message occurs when the dump succeeded, but returned one or more errors unknown to
\fIAmanda\fR\&.
.RE
.PP
\fBerror\fR
.RS 4
Send an email only on error messages\&.
.RE
.PP
\fBnever\fR
.RS 4
Never send an email\&.
.RE
.RE
.PP
\fBdumpcycle\fR \fI int\fR
.RS 4
Default:
\fI10 days\fR\&. The number of days in the backup cycle\&. Each disk will get a full backup at least this often\&. Setting this to zero tries to do a full backup each run\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
This parameter may also be set in a specific
\fBdumptype\fR
(see below)\&. This value sets the default for all
\fBdumptype\fRs so must appear in
\fBamanda\&.conf\fR
before any
\fBdumptype\fRs are defined\&.
.sp .5v
.RE
.RE
.PP
\fBrunspercycle\fR \fI int\fR
.RS 4
Default:
\fIsame as dumpcycle\fR\&. The number of amdump runs in
\fBdumpcycle\fR
days\&. A value of 0 means the same value as
\fBdumpcycle\fR\&. A value of \-1 means guess the number of runs from the
\fBtapelist\fR(5)
file, which is the number of tapes used in the last
\fBdumpcycle\fR
days /
\fBruntapes\fR\&.
.RE
.PP
\fBtapecycle\fR \fI int\fR
.RS 4
Default:
\fI15 tapes\fR\&. Typically tapes are used by
\fIAmanda\fR
in an ordered rotation\&. The
\fBtapecycle\fR
parameter defines the size of that rotation\&. The number of tapes in rotation must be larger than the number of tapes required for a complete dump cycle (see the
\fBdumpcycle\fR
parameter)\&.
.sp
This is calculated by multiplying the number of
\fBamdump\fR
runs per dump cycle (\fBrunspercycle\fR
parameter) times the number of tapes used per run (\fBruntapes\fR
parameter)\&. Typically two to four times this calculated number of tapes are in rotation\&. While
\fIAmanda\fR
is always willing to use a new tape in its rotation, it refuses to reuse a tape until at least \'\fBtapecycle\fR
\-1\' number of other tapes have been used\&.
.sp
It is considered good administrative practice to set the
\fBtapecycle\fR
parameter slightly lower than the actual number of tapes in rotation\&. This allows the administrator to more easily cope with damaged or misplaced tapes or schedule adjustments that call for slight adjustments in the rotation order\&.
.RE
.PP
\fBusetimestamps\fR \fI bool\fR
.RS 4
Default:
\fBYes\fR\&. This option allows Amanda to track multiple runs per calendar day\&. The only reason one might disable it is that Amanda versions before 2\&.5\&.1 can\'t read logfiles written when this option was enabled\&.
.RE
.PP
\fBlabel_new_tapes\fR \fI string\fR
.RS 4
Default: not set\&. When set, this directive will cause
\fIAmanda\fR
to automatically write an
\fIAmanda\fR
tape label to any blank tape she encounters\&. This option is DANGEROUS because when set,
\fIAmanda\fR
will ERASE any non\-\fIAmanda\fR
tapes you may have, and may also ERASE any near\-failing tapes\&. Use with caution\&.
.sp
When using this directive, specify the template for new tape labels\&. The template should contain some number of contiguous \'%\' characters, which will be replaced with a generated number\&. Be sure to specify enough \'%\' characters that you do not run out of tape labels\&. Example:
\fBlabel_new_tapes "DailySet1\-%%%"\fR
.RE
.PP
\fBdumpuser\fR \fI string\fR
.RS 4
Default:
\fIamanda\fR\&. The login name
\fIAmanda\fR
uses to run the backups\&. The backup client hosts must allow access from the tape server host as this user via
\fB\&.rhosts\fR
or
\fB\&.amandahosts\fR, depending on how the
\fIAmanda\fR
software was built\&.
.RE
.PP
\fBprinter\fR string
.RS 4
Printer to use when doing tape labels\&. See the
\fBlbl\-templ\fR
\fBtapetype\fR
option\&.
.RE
.PP
\fBtapedev\fR string
.RS 4
Default:
null:\&. The device name, referencing the name of a "device" section in the configuration file\&. See
\fBamanda-devices\fR(7)
for more information on device names\&.
.sp
If a tape changer is configured (see the
\fBtpchanger\fR
option), this option might not be used\&.
.sp
If
\fBtapedev\fR
is
\fBnull:\fR, programs such as
\fBamdump\fR
will run normally but all images will be thrown away\&. This should only be used for debugging and testing, and probably only with the
\fBrecord\fR
option set to
\fIno\fR\&.
.RE
.PP
\fBdevice_property\fR string string
.RS 4
These options can set various device properties\&. See
\fBamanda-devices\fR(7)
for more information on device properties and their syntax\&. Both strings are always quoted; the first string contains the name of the property to set, and the second contains its value\&. For example, to set a fixed block size of 128k, write:
.nf
device_property "BLOCK_SIZE" "128k"
.fi
.RE
.PP
\fBproperty\fR [append] string string+
.RS 4
These options can set various properties, they can be used by third party software to store information in the configuration file\&. Both strings are quoted; the first string contains the name of the property to set, and the others contains its values\&.
\fBappend\fR
keyword append the values to the list of values for that property\&.
.RE
.PP
\fBtpchanger\fR string
.RS 4
Default:
\fInone\fR\&. The name of the tape changer\&. If a tape changer is not configured, this option is not used and should be commented out of the configuration file\&.
.sp
If a tape changer is configured, choose one of the changer scripts (e\&.g\&.
\fBchg\-scsi\fR) and enter that here\&.
.RE
.PP
\fBchangerdev\fR string
.RS 4
Default:
/dev/null\&. A tape changer configuration parameter\&. Usage depends on the particular changer defined with the
\fBtpchanger\fR
option\&.
.RE
.PP
\fBchangerfile\fR string
.RS 4
Default:
/usr/adm/amanda/log/changer\-status\&. A tape changer configuration parameter\&. Usage depends on the particular changer defined with the
\fBtpchanger\fR
option\&.
.RE
.PP
\fBruntapes\fR int
.RS 4
Default:
1\&. The maximum number of tapes used in a single run\&. If a tape changer is not configured, this option is not used and should be commented out of the configuration file\&.
.sp
If a tape changer is configured, this may be set larger than one to let
\fIAmanda\fR
write to more than one tape\&.
.sp
Note that this is an upper bound on the number of tapes, and
\fIAmanda\fR
may use less\&.
.sp
Also note that as of this release,
\fIAmanda\fR
does not support true tape overflow\&. When it reaches the end of one tape, the backup image
\fIAmanda\fR
was processing starts over again on the next tape\&.
.RE
.PP
\fBmaxdumpsize\fR int
.RS 4
Default:
\fIruntapes\fR*\fItape_length\fR\&. Maximum number of bytes the planner will schedule for a run\&.
.sp
The default unit is Kbytes if it is not specified\&.
.RE
.PP
\fBtaperalgo\fR [first|firstfit|largest|largestfit|smallest|last]
.RS 4
Default:
\fIfirst\fR\&. The algorithm used to choose which dump image to send to the taper\&.
.PP
\fBfirst\fR
.RS 4
First in, first out\&.
.RE
.PP
\fBfirstfit\fR
.RS 4
The first dump image that will fit on the current tape\&.
.RE
.PP
\fBlargest\fR
.RS 4
The largest dump image\&.
.RE
.PP
\fBlargestfit\fR
.RS 4
The largest dump image that will fit on the current tape\&.
.RE
.PP
\fBsmallest\fR
.RS 4
The smallest dump image\&.
.RE
.PP
\fBlast\fR
.RS 4
Last in, first out\&.
.RE
.RE
.PP
\fBlabelstr\fR \fI string\fR
.RS 4
Default:
\fI\&.*\fR\&. The tape label constraint regular expression\&. All tape labels generated (see
\fBamlabel\fR(8)) and used by this configuration must match the regular expression\&. If multiple configurations are run from the same tape server host, it is helpful to set their labels to different strings (for example, "DAILY[0\-9][0\-9]*" vs\&. "ARCHIVE[0\-9][0\-9]*") to avoid overwriting each other\'s tapes\&.
.RE
.PP
\fBtapetype\fR \fI identifier\fR
.RS 4
Default:
\fI"EXABYTE"\fR\&. The type of tape drive associated with
\fBtapedev\fR
or
\fBtpchanger\fR\&. This refers to one of the defined
\fBtapetype\fRs in the config file (see below), which specify various tape parameters, like the
\fBlength\fR,
\fBfilemark\fR
size, and
\fBspeed\fR
of the tape media and device\&.
.RE
.PP
\fBctimeout\fR int
.RS 4
Default:
\fI30 seconds\fR\&. Maximum amount of time that
\fBamcheck\fR
will wait for each client host\&.
.RE
.PP
\fBdtimeout\fR int
.RS 4
Default:
\fI1800 seconds\fR\&. Amount of idle time per disk on a given client that a
\fBdumper\fR
running from within
\fBamdump\fR
will wait before it fails with a data timeout error\&.
.RE
.PP
\fBetimeout\fR int
.RS 4
Default:
\fI300 seconds\fR\&. Amount of time per estimate on a given client that the
\fBplanner\fR
step of
\fBamdump\fR
will wait to get the dump size estimates (note: Amanda runs up to 3 estimates for each DLE)\&. For instance, with the default of 300 seconds and four DLE\'s, each estimating level 0 and level 1 on client A,
\fBplanner\fR
will wait up to 40 minutes for that machine\&. A negative value will be interpreted as a total amount of time to wait per client instead of per disk\&.
.RE
.PP
\fBconnect_tries\fR int
.RS 4
Default:
\fI3\fR\&. How many times the server will try a connection\&.
.RE
.PP
\fBreq_tries\fR int
.RS 4
Default:
\fI3\fR\&. How many times the server will resend a REQ packet if it doesn\'t get the ACK packet\&.
.RE
.PP
\fBnetusage\fR int
.RS 4
Default:
\fI8000 Kbps\fR\&. The maximum network bandwidth allocated to
\fIAmanda\fR, in Kbytes per second\&. See also the
\fBinterface\fR
section\&.
.RE
.PP
\fBinparallel\fR int
.RS 4
Default:
10\&. The maximum number of backups that
\fIAmanda\fR
will attempt to run in parallel\&.
\fIAmanda\fR
will stay within the constraints of network bandwidth and holding disk space available, so it doesn\'t hurt to set this number a bit high\&. Some contention can occur with larger numbers of backups, but this effect is relatively small on most systems\&.
.RE
.PP
\fBdisplayunit\fR "k|m|g|t"
.RS 4
Default:
"k"\&. The unit used to print many numbers, k=kilo, m=mega, g=giga, t=tera\&.
.RE
.PP
\fBdumporder\fR string
.RS 4
Default:
\fItttTTTTTTT\fR\&. The priority order of each dumper:
.sp
.nf
s: smallest size
S: largest size
t: smallest time
T: largest time
b: smallest bandwidth
B: largest bandwidth
.fi
.RE
.PP
\fBmaxdumps\fR int
.RS 4
Default:
1\&. The maximum number of backups from a single host that
\fIAmanda\fR
will attempt to run in parallel\&. See also the
\fBinparallel\fR
option\&.
.sp
Note that this parameter may also be set in a specific
\fBdumptype\fR
(see below)\&. This value sets the default for all
\fBdumptype\fRs so must appear in
\fBamanda\&.conf\fR
before any
\fBdumptype\fRs are defined\&.
.RE
.PP
\fBbumpsize\fR int
.RS 4
Default:
\fI10 Mbytes\fR\&. The minimum savings required to trigger an automatic bump from one incremental level to the next, expressed as size\&. If
\fIAmanda\fR
determines that the next higher backup level will be this much smaller than the current level, it will do the next level\&. The value of this parameter is used only if the parameter
\fIbumppercent\fR
is set to 0\&.
.sp
The default unit is Kbytes if it is not specified\&.
.sp
The global setting of this parameter can be overwritten inside of a dumptype\-definition\&.
.sp
See also the options
\fBbumppercent\fR,
\fBbumpmult\fR
and
\fBbumpdays\fR\&.
.RE
.PP
\fBbumppercent\fR int
.RS 4
Default:
\fI0 percent\fR\&. The minimum savings required to trigger an automatic bump from one incremental level to the next, expressed as percentage of the current size of the DLE (size of current level 0)\&. If
\fIAmanda\fR
determines that the next higher backup level will be this much smaller than the current level, it will do the next level\&.
.sp
If this parameter is set to 0, the value of the parameter
\fIbumpsize\fR
is used to trigger bumping\&.
.sp
The global setting of this parameter can be overwritten inside of a dumptype\-definition\&.
.sp
See also the options
\fBbumpsize\fR,
\fBbumpmult\fR
and
\fBbumpdays\fR\&.
.RE
.PP
\fBbumpmult\fR \fI float\fR
.RS 4
Default:
1\&.5\&. The bump size multiplier\&.
\fIAmanda\fR
multiplies
\fBbumpsize\fR
by this factor for each level\&. This prevents active filesystems from bumping too much by making it harder to bump to the next level\&. For example, with the default
\fBbumpsize\fR
and
\fBbumpmult\fR
set to 2\&.0, the bump threshold will be 10 Mbytes for level one, 20 Mbytes for level two, 40 Mbytes for level three, and so on\&.
.sp
The global setting of this parameter can be overwritten inside of a dumptype\-definition\&.
.RE
.PP
\fBbumpdays\fR \fI int\fR
.RS 4
Default:
\fI2 days\fR\&. To insure redundancy in the dumps,
\fIAmanda\fR
keeps filesystems at the same incremental level for at least
\fBbumpdays\fR
days, even if the other bump threshold criteria are met\&.
.sp
The global setting of this parameter can be overwritten inside of a dumptype\-definition\&.
.RE
.PP
\fBdiskfile\fR \fI string\fR
.RS 4
Default:
\fIdisklist\fR\&. The file name for the
\fIdisklist\fR
file holding client hosts, disks and other client dumping information\&.
.RE
.PP
\fBinfofile\fR \fI string\fR
.RS 4
Default:
/usr/adm/amanda/curinfo\&. The file or directory name for the historical information database\&. If
\fIAmanda\fR
was configured to use DBM databases, this is the base file name for them\&. If it was configured to use text formated databases (the default), this is the base directory and within here will be a directory per client, then a directory per disk, then a text file of data\&.
.RE
.PP
\fBlogdir\fR \fI string\fR
.RS 4
Default:
/usr/adm/amanda\&. The directory for the
\fBamdump\fR
and
\fBlog\fR
files\&.
.RE
.PP
\fBindexdir\fR \fI string\fR
.RS 4
Default
/usr/adm/amanda/index\&. The directory where index files (backup image catalogues) are stored\&. Index files are only generated for filesystems whose
\fBdumptype\fR
has the
\fBindex\fR
option enabled\&.
.RE
.PP
\fBtapelist\fR \fI string\fR
.RS 4
Default:
\fItapelist\fR\&. The file name for the active
\fBtapelist\fR(5)\&.
\fIAmanda\fR
maintains this file with information about the active set of tapes\&.
.RE
.PP
\fBdevice_output_buffer_size\fR \fI int\fR
.RS 4
Default:
1280k\&. Controls the amount of memory used by
\fIAmanda\fR
to hold data as it is read from the network or disk before it is written to the output device\&. Higher values may be useful on fast tape drives and optical media\&.
.sp
The default unit is bytes if it is not specified\&.
.RE
.PP
\fBtapebufs\fR \fI int\fR
.RS 4
Default:
20\&. This option is deprecated; use the
\fBdevice_output_buffer_size\fR
directive instead\&.
\fBtapebufs\fR
works the same way, but the number specified is multiplied by the device blocksize prior to use\&.
.RE
.PP
\fBreserve\fR \fI number\fR
.RS 4
Default:
100\&. The part of holding\-disk space that should be reserved for incremental backups if no tape is available, expressed as a percentage of the available holding\-disk space (0\-100)\&. By default, when there is no tape to write to, degraded mode (incremental) backups will be performed to the holding disk\&. If full backups should also be allowed in this case, the amount of holding disk space reserved for incrementals should be lowered\&.
.RE
.PP
\fBautoflush\fR \fI bool\fR
.RS 4
Default:
\fIoff\fR\&. Whether an amdump run will flush the dumps from holding disk to tape\&.
.RE
.PP
\fBamrecover_do_fsf\fR \fI bool\fR
.RS 4
Default:
\fIon\fR\&. Amrecover will call amrestore with the \-f flag for faster positioning of the tape\&.
.RE
.PP
\fBamrecover_check_label\fR \fI bool\fR
.RS 4
Default:
\fIon\fR\&. Amrecover will call amrestore with the \-l flag to check the label\&.
.RE
.PP
\fBamrecover_changer\fR \fI string\fR
.RS 4
Default: \'\'\&. Amrecover will use the changer if you use \'settape <string>\' and that string is the same as the amrecover_changer setting\&.
.RE
.PP
\fBcolumnspec\fR \fI string\fR
.RS 4
Defines the width of columns
\fBamreport\fR
should use\&.
\fIString\fR
is a comma (\',\') separated list of triples\&. Each triple consists of three parts which are separated by a equal sign (\'=\') and a colon (\':\') (see the example)\&. These three parts specify:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
the name of the column, which may be:
.nf
	Compress (compression ratio)
	Disk (client disk name)
	DumpRate (dump rate in KBytes/sec)
	DumpTime (total dump time in hours:minutes)
	HostName (client host name)
	Level (dump level)
	OrigKB (original image size in KBytes)
	OutKB (output image size in KBytes)
	TapeRate (tape writing rate in KBytes/sec)
	TapeTime (total tape time in hours:minutes)
.fi
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
the amount of space to display before the column (used to get whitespace between columns)\&.
.sp
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
the width of the column itself\&. If set to a negative value, the width will be calculated on demand to fit the largest entry in this column\&.
.RE
Here is an example:
.sp
.nf
columnspec "Disk=1:18,HostName=0:10,OutKB=1:7"
.fi
.sp
The above will display the disk information in 18 characters and put one space before it\&. The hostname column will be 10 characters wide with no space to the left\&. The output KBytes column is seven characters wide with one space before it\&.
.RE
.PP
\fBincludefile\fR \fI string\fR
.RS 4
Default:
\fInone\fR\&. The name of an
\fIAmanda\fR
configuration file to include within the current file\&. Useful for sharing dumptypes, tapetypes and interface definitions among several configurations\&. Relative pathnames are relative to the configuration directory\&.
.RE
.PP
\fBdebug_auth\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the auth module
.RE
.PP
\fBdebug_event\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the event module
.RE
.PP
\fBdebug_holding\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the holdingdisk module
.RE
.PP
\fBdebug_protocol\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the protocol module
.RE
.PP
\fBdebug_planner\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the planner process
.RE
.PP
\fBdebug_driver\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the driver process
.RE
.PP
\fBdebug_dumper\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the dumper process
.RE
.PP
\fBdebug_chunker\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the chunker process
.RE
.PP
\fBdebug_taper\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the taper process
.RE
.PP
\fBflush\-threshold\-dumped\fR int
.RS 4
Default:
\fI0\fR\&.
\fIAmanda\fR
will not begin writing data to a new volume until the amount of data on the holding disk is at least this percentage of the volume size\&. In other words,
\fIAmanda\fR
will not begin until the inequality
h > t \(mu d
is satisfied, where
h
is the amount of data on the holding disk,
t
is the capacity of a volume, and
d
is this parameter, expressed as a percentage\&. This parameter may be larger than 100%, for example to keep more recent dumps on the holding disk for faster recovery\&.
.sp
Needless to say, your holding disk must be big enough that this criterion could be satisfied\&. If the holding disk cannot be used for a particular dump (because, for example, there is no remaining holding space) then
\fIAmanda\fR
will disregard the constraint specified by this setting and start a new volume anyway\&. Once writing to a volume has begun, this constraint is not applied unless and until a new volume is needed\&.
.sp
The value of this parameter may not exceed than that of the
\fBflush\-threshold\-scheduled\fR
parameter\&.
.RE
.PP
\fBflush\-threshold\-scheduled\fR int
.RS 4
Default:
\fI0\fR\&.
\fIAmanda\fR
will not begin writing data to a new volume until the sum of the amount of data on the holding disk and the estimated amount of data remaining to be dumped during this run is at least this percentage of the volume size\&. In other words,
\fIAmanda\fR
will not begin until the inequality
h + s > t \(mu d
is satisfied, where
h
is the amount of data on the holding disk,
s
is the total amount of data scheduled for this run but not dumped yet,
t
is the capacity of a volume, and
d
is this parameter, expressed as a percentage\&. This parameter may be larger than 100%\&.
.sp
Needless to say, your holding disk must be big enough that this criterion could be satisfied\&. If the holding disk cannot be used for a particular dump (because, for example, there is no remaining holding space) then
\fIAmanda\fR
will disregard the constraint specified by this setting and start a new volume anyway\&. Once writing to a volume has begun, this constraint is not applied unless and until a new volume is needed\&.
.sp
The value of this parameter may not be less than that of the
\fBflush\-threshold\-dumped\fR
or
\fBtaperflush\fR
parameters\&.
.RE
.PP
\fBtaperflush\fR int
.RS 4
Default:
\fI0\fR\&. At the end of a run,
\fIAmanda\fR
will start a new tape to flush remaining data if there is more data on the holding disk at the end of a run than this setting allows; the amount is specified as a percentage of the capacity of a single volume\&. In other words, at the end of a run,
\fIAmanda\fR
will begin a new tape if the inequality
h > t \(mu f
is satisfied, where
h
is the amount of data remaining on the holding disk from this or previous runs,
t
is the capacity of a volume, and
f
is this parameter, expressed as a percentage\&. This parameter may be greater than 100%\&.
.sp
The value of this parameter may not exceed that of the
\fBflush\-threshold\-scheduled\fR
parameter\&.;
\fBautoflush\fR
must be set to \'yes\' if
\fBtaperflush\fR
is greater than 0\&.
.RE
.PP
\fBreserved\-udp\-port\fR int,int
.RS 4
Default: \-\-with\-udpportrange or
\fI512,1023\fR\&. Reserved udp port that will be used (bsd, bsdudp)\&. Range is inclusive\&.
.RE
.PP
\fBreserved\-tcp\-port\fR int,int
.RS 4
Default: \-\-with\-low\-tcpportrange or
\fI512,1023\fR\&. Reserved tcp port that will be used (bsdtcp)\&. Range is inclusive\&.
.RE
.PP
\fBunreserved\-tcp\-port\fR int,int
.RS 4
Default: \-\-with\-tcpportrange or
\fI1024,65535\fR\&. Unreserved tcp port that will be used (bsd, bsdudp)\&. Range is inclusive\&.
.RE
.SH "HOLDINGDISK SECTION"
.PP
The
\fBamanda\&.conf\fR
file may define one or more holding disks used as buffers to hold backup images before they are written to tape\&. The syntax is:
.nf
holdingdisk \fIname\fR {
    \fIholdingdisk\-option\fR \fIholdingdisk\-value\fR
    \&.\&.\&.
}
.fi
.PP
\fIName\fR
is a logical name for this holding disk\&.
.PP
The options and values are:
.PP
\fBcomment\fR \fI string\fR
.RS 4
Default:
\fInone\fR\&. A comment string describing this holding disk\&.
.RE
.PP
\fBdirectory\fR \fI disk\fR
.RS 4
Default:
/dumps/amanda\&. The path to this holding area\&.
.RE
.PP
\fBuse\fR \fI int\fR
.RS 4
Default:
\fI0 Gb\fR\&. Amount of space that can be used in this holding disk area\&. If the value is zero, all available space on the file system is used\&. If the value is negative,
\fIAmanda\fR
will use all available space minus that value\&.
.RE
.PP
\fBchunksize\fR \fI int\fR
.RS 4
Default:
\fI1 Gb\fR\&. Holding disk chunk size\&. Dumps larger than the specified size will be stored in multiple holding disk files\&. The size of each chunk will not exceed the specified value\&. However, even though dump images are split in the holding disk, they are concatenated as they are written to tape, so each dump image still corresponds to a single continuous tape section\&.
.sp
The default unit is Kbytes if it is not specified\&.
.sp
If 0 is specified,
\fIAmanda\fR
will create holding disk chunks as large as ((INT_MAX/1024)\-64) Kbytes\&.
.sp
Each holding disk chunk includes a 32 Kbyte header, so the minimum chunk size is 64 Kbytes (but that would be really silly)\&.
.sp
Operating systems that are limited to a maximum file size of 2 Gbytes actually cannot handle files that large\&. They must be at least one byte less than 2 Gbytes\&. Since
\fIAmanda\fR
works with 32 Kbyte blocks, and to handle the final read at the end of the chunk, the chunk size should be at least 64 Kbytes (2 * 32 Kbytes) smaller than the maximum file size, e\&.g\&. 2047 Mbytes\&.
.RE
.SH "DUMPTYPE SECTION"
.PP
The
\fBamanda.conf\fR(5)
file may define multiple sets of backup options and refer to them by name from the
\fBdisklist\fR(5)
file\&. For instance, one set of options might be defined for file systems that can benefit from high compression, another set that does not compress well, another set for file systems that should always get a full backup and so on\&.
.PP
A set of backup options are entered in a
\fBdumptype\fR
section, which looks like this:
.nf
define dumptype "\fIname\fR" {
    \fIdumptype\-option\fR \fIdumptype\-value\fR
    \&.\&.\&.
}
.fi
.PP
\fIName\fR
is the name of this set of backup options\&. It is referenced from the
\fBdisklist\fR(5)
file\&.
.PP
Some of the options in a
\fBdumptype\fR
section are the same as those in the main part of
\fBamanda.conf\fR(5)\&. The main option value is used to set the default for all
\fBdumptype\fR
sections\&. For instance, setting
\fBdumpcycle\fR
to 50 in the main part of the config file causes all following
\fBdumptype\fR
sections to start with that value, but the value may be changed on a section by section basis\&. Changes to variables in the main part of the config file must be done before (earlier in the file) any
\fBdumptype\fRs are defined\&.
.PP
The dumptype options and values are:
.PP
\fBauth\fR \fI string\fR
.RS 4
Default:
\fIbsd\fR\&. Type of authorization to perform between tape server and backup client hosts\&. See
\fBamanda-auth\fR(7)
for more detail\&.
.RE
.PP
\fBamandad_path\fR \fI string\fR
.RS 4
Default:
\fI$libexec/amandad\fR\&. Specify the amandad path of the client, only use with rsh/ssh authentification\&.
.RE
.PP
\fBclient_username\fR \fI string\fR
.RS 4
Default:
\fICLIENT_LOGIN\fR\&. Specify the username to connect on the client, only use with rsh/ssh authentification\&.
.RE
.PP
\fBbumpsize\fR int
.RS 4
Default:
\fI10 Mbytes\fR\&. The minimum savings required to trigger an automatic bump from one incremental level to the next, expressed as size\&. If
\fIAmanda\fR
determines that the next higher backup level will be this much smaller than the current level, it will do the next level\&. The value of this parameter is used only if the parameter
\fIbumppercent\fR
is set to 0\&.
.sp
The default unit is Kbytes if it is not specified\&.
.sp
See also the options
\fBbumppercent\fR,
\fBbumpmult\fR
and
\fBbumpdays\fR\&.
.RE
.PP
\fBbumppercent\fR int
.RS 4
Default:
\fI0 percent\fR\&. The minimum savings required to trigger an automatic bump from one incremental level to the next, expressed as percentage of the current size of the DLE (size of current level 0)\&. If
\fIAmanda\fR
determines that the next higher backup level will be this much smaller than the current level, it will do the next level\&.
.sp
If this parameter is set to 0, the value of the parameter
\fIbumpsize\fR
is used to trigger bumping\&.
.sp
See also the options
\fBbumpsize\fR,
\fBbumpmult\fR
and
\fBbumpdays\fR\&.
.RE
.PP
\fBbumpmult\fR \fI float\fR
.RS 4
Default:
1\&.5\&. The bump size multiplier\&.
\fIAmanda\fR
multiplies
\fBbumpsize\fR
by this factor for each level\&. This prevents active filesystems from bumping too much by making it harder to bump to the next level\&. For example, with the default
\fBbumpsize\fR
and
\fBbumpmult\fR
set to 2\&.0, the bump threshold will be 10 Mbytes for level one, 20 Mbytes for level two, 40 Mbytes for level three, and so on\&.
.RE
.PP
\fBbumpdays\fR \fI int\fR
.RS 4
Default:
\fI2 days\fR\&. To insure redundancy in the dumps,
\fIAmanda\fR
keeps filesystems at the same incremental level for at least
\fBbumpdays\fR
days, even if the other bump threshold criteria are met\&.
.RE
.PP
\fBcomment\fR \fI string\fR
.RS 4
Default:
\fInone\fR\&. A comment string describing this set of backup options\&.
.RE
.PP
\fBcomprate\fR \fIfloat\fR [, \fIfloat\fR ]
.RS 4
Default:
0\&.50,
0\&.50\&. The expected full and incremental compression factor for dumps\&. It is only used if
\fIAmanda\fR
does not have any history information on compression rates for a filesystem, so should not usually need to be set\&. However, it may be useful for the first time a very large filesystem that compresses very little is backed up\&.
.RE
.PP
\fBcompress [client|server]\fR \fI string\fR
.RS 4
Default:
\fIclient fast\fR\&. If
\fIAmanda\fR
does compression of the backup images, it can do so either on the backup client host before it crosses the network or on the tape server host as it goes from the network into the holding disk or to tape\&. Which place to do compression (if at all) depends on how well the dump image usually compresses, the speed and load on the client or server, network capacity, holding disk capacity, availability of tape hardware compression, etc\&.
.sp
For either type of compression,
\fIAmanda\fR
also allows the selection of three styles of compression\&.
\fBBest\fR
is the best compression available, often at the expense of CPU overhead\&.
\fBFast\fR
is often not as good a compression as
\fBbest\fR, but usually less CPU overhead\&. Or to specify
\fBCustom\fR
to use your own compression method\&. (See dumptype custom\-compress in example/amanda\&.conf for reference)
.sp
So the
\fBcompress\fR
options line may be one of:
.PP
compress none
.RS 4
.RE
.PP
compress client fast
.RS 4
.RE
.PP
compress client best
.RS 4
.RE
.PP
compress client custom
.RS 4
Specify
\fIclient_custom_compress\fR
"PROG"
.sp
PROG must not contain white space and it must accept \-d for uncompress\&.
.RE
.PP
compress server fast
.RS 4
.RE
.PP
compress server best
.RS 4
.RE
.PP
compress server custom
.RS 4
Specify
\fIserver_custom_compress\fR
"PROG"
.sp
PROG must not contain white space and it must accept \-d for uncompress\&.
.RE
.sp
Note that some tape devices do compression and this option has nothing to do with whether that is used\&. If hardware compression is used (usually via a particular tape device name or
\fBmt\fR
option),
\fIAmanda\fR
(software) compression should be disabled\&.
.RE
.PP
\fBdumpcycle\fR \fI int\fR
.RS 4
Default:
\fI10 days\fR\&. The number of days in the backup cycle\&. Each disk using this set of options will get a full backup at least this of ten\&. Setting this to zero tries to do a full backup each run\&.
.RE
.PP
\fBencrypt [none|client|server]\fR
.RS 4
Default:
\fInone\fR\&. To encrypt backup images, it can do so either on the backup client host before it crosses the network or on the tape server host as it goes from the network into the holding disk or to tape\&.
.sp
So the
\fBencrypt\fR
options line may be one of:
.PP
encrypt none
.RS 4
.RE
.PP
encrypt client
.RS 4
Specify client_encrypt "PROG"
.sp
PROG must not contain white space\&.
.sp
Specify client_decrypt_option "decryption\-parameter" Default: "\-d"
.sp
decryption\-parameter must not contain white space\&.
.sp
(See dumptype client\-encrypt\-nocomp in example/amanda\&.conf for reference)
.RE
.PP
encrypt server
.RS 4
Specify server_encrypt "PROG"
.sp
PROG must not contain white space\&.
.sp
Specify server_decrypt_option "decryption\-parameter" Default: "\-d"
.sp
decryption\-parameter must not contain white space\&.
.sp
(See dumptype server\-encrypt\-fast in example/amanda\&.conf for reference)
.RE
.sp
Note that current logic assumes compression then encryption during backup(thus decrypt then uncompress during restore)\&. So specifying client\-encryption AND server\-compression is not supported\&.
\fIamcrypt\fR
which is a wrapper of
\fIaespipe\fR
is provided as a reference symmetric encryption program\&.
.RE
.PP
\fBestimate\fR \fIclient|calcsize|server\fR
.RS 4
Default:
\fIclient\fR\&. Determine the way
\fIAmanda\fR
does it\'s estimate\&.
.PP
client
.RS 4
Use the same program as the dumping program, this is the most accurate way to do estimates, but it can take a long time\&.
.RE
.PP
calcsize
.RS 4
Use a faster program to do estimates, but the result is less accurate\&.
.RE
.PP
server
.RS 4
Use only statistics from the previous run to give an estimate, it takes only a few seconds but the result is not accurate if your disk usage changes from day to day\&.
.RE
.RE
.PP
\fBexclude\fR [ list|file ][[optional][ append ][ \fIstring\fR ]+]
.RS 4
Default:
\fIfile\fR\&. There are two exclude lists,
\fBexclude file\fR
and
\fBexclude list\&.\fR
With
\fBexclude file\fR
, the
\fIstring\fR
is a
\fBGNU\-tar\fR
exclude expression\&. With
\fBexclude list\fR
, the
\fIstring\fR
is a file name on the client containing
\fBGNU\-tar\fR
exclude expressions\&. The path to the specified exclude list file, if present (see description of \'optional\' below), must be readable by the
\fIAmanda\fR
user\&.
.sp
All exclude expressions are concatenated in one file and passed to
\fBGNU\-tar\fR
as an
\fB\-\-exclude\-from\fR
argument\&.
.sp
Exclude expressions must always be specified as relative to the head directory of the DLE\&.
.sp
With the
\fBappend\fR
keyword, the
\fIstring\fR
is appended to the current list, without it, the
\fIstring\fR
overwrites the list\&.
.sp
If
\fBoptional\fR
is specified for
\fBexclude list\fR, then amcheck will not complain if the file doesn\'t exist or is not readable\&.
.sp
For
\fBexclude list\fR, if the file name is relative, the disk name being backed up is prepended\&. So if this is entered:
.nf
    exclude list "\&.amanda\&.excludes"
.fi
the actual file used would be
/var/\&.amanda\&.excludes
for a backup of
/var,
/usr/local/\&.amanda\&.excludes
for a backup of
/usr/local, and so on\&.
.RE
.PP
\fBholdingdisk\fR [ never|auto|required ]
.RS 4
Default:
\fIauto\fR\&. Whether a holding disk should be used for these backups or whether they should go directly to tape\&. If the holding disk is a portion of another file system that
\fIAmanda\fR
is backing up, that file system should refer to a dumptype with
\fBholdingdisk\fR
set to
\fInever\fR
to avoid backing up the holding disk into itself\&.
.PP
\fBnever\fR|no|false|off
.RS 4
Never use a holdingdisk, the dump will always go directly to tape\&. There will be no dump if you have a tape error\&.
.RE
.PP
\fBauto\fR|yes|true|on
.RS 4
Use the holding disk, unless there is a problem with the holding disk, the dump won\'t fit there or the medium doesn\'t require spooling (e\&.g\&., VFS device)
.RE
.PP
\fBrequired\fR
.RS 4
Always dump to holdingdisk, never directly to tape\&. There will be no dump if it doesn\'t fit on holdingdisk
.RE
.RE
.PP
\fBignore\fR \fI boolean\fR
.RS 4
Default:
\fIno\fR\&. Whether disks associated with this backup type should be backed up or not\&. This option is useful when the
\fIdisklist\fR
file is shared among several configurations, some of which should not back up all the listed file systems\&.
.RE
.PP
\fBinclude\fR [ list|file ][[optional][ append ][ \fIstring\fR ]+]
.RS 4
Default:
\fIfile\fR
"\&."\&. There are two include lists,
\fBinclude file\fR
and
\fBinclude list\&.\fR
With
\fBinclude file\fR
, the
\fIstring\fR
is a glob expression\&. With
\fBinclude list\fR
, the
\fIstring\fR
is a file name on the client containing glob expressions\&.
.sp
All include expressions are expanded by
\fIAmanda\fR, concatenated in one file and passed to
\fBGNU\-tar\fR
as a
\fB\-\-files\-from\fR
argument\&. They must start with "\&./" and contain no other "/"\&.
.sp
Include expressions must always be specified as relative to the head directory of the DLE\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
For globbing to work at all, even the limited single level, the top level directory of the DLE must be readable by the
\fIAmanda\fR
user\&.
.sp .5v
.RE
With the
\fBappend\fR
keyword, the
\fIstring\fR
is appended to the current list, without it, the
\fIstring\fR
overwrites the list\&.
.sp
If
\fBoptional\fR
is specified for
\fBinclude list,\fR
then amcheck will not complain if the file doesn\'t exist or is not readable\&.
.sp
For
\fBinclude list\fR, If the file name is relative, the disk name being backed up is prepended\&.
.RE
.PP
\fBindex\fR \fI boolean\fR
.RS 4
Default:
\fIno\fR\&. Whether an index (catalogue) of the backup should be generated and saved in
\fBindexdir\fR\&. These catalogues are used by the
\fBamrecover\fR
utility\&.
.RE
.PP
\fBkencrypt\fR \fI boolean\fR
.RS 4
Default:
\fIno\fR\&. Whether the backup image should be encrypted by Kerberos as it is sent across the network from the backup client host to the tape server host\&.
.RE
.PP
\fBmaxdumps\fR \fI int\fR
.RS 4
Default:
1\&. The maximum number of backups from a single host that
\fIAmanda\fR
will attempt to run in parallel\&. See also the main section parameter
\fBinparallel\fR\&.
.RE
.PP
\fBmaxpromoteday\fR \fI int\fR
.RS 4
Default:
10000\&. The maximum number of day for a promotion, set it 0 if you don\'t want promotion, set it to 1 or 2 if your disks get overpromoted\&.
.RE
.PP
\fBpriority\fR \fI string\fR
.RS 4
Default:
\fImedium\fR\&. When there is no tape to write to,
\fIAmanda\fR
will do incremental backups in priority order to the holding disk\&. The priority may be high (2), medium (1), low (0) or a number of your choice\&.
.RE
.PP
\fBprogram\fR [DUMP|GNUTAR|APPLICATION]
.RS 4
Default:
\fIDUMP\fR\&. The type of backup to perform\&. Valid values are:
.PP
\fBDUMP\fR
.RS 4
The native operating system backup program\&.
.RE
.PP
\fBGNUTAR\fR
.RS 4
To use GNU\-tar or to do PC backups using Samba\&.
.RE
.PP
\fBAPPLICATION\fR
.RS 4
To use an application\-tool, see the
\fIapplication\fR
option\&.
.RE
.RE
.PP
\fBapplication\fR \fI string\fR
.RS 4
No default\&. Must be the name of an application\-tool if
\fIprogram\fR
is set to
\fIAPPLICATION\fR\&. See APPLICATION SECTION below\&.
.RE
.PP
\fBscript\fR \fI string\fR
.RS 4
No default\&. Must be the name of a script\-tool\&. You can have many script\&. See SCRIPT SECTION below\&.
.RE
.PP
\fBproperty\fR [append] \fIstring\fR \fIstring\fR+
.RS 4
These options can set various properties, they can be used by third party software to store information in the configuration file\&. Both strings are quoted; the first string contains the name of the property to set, and the others contains its values\&.
\fBappend\fR
keyword append the values to the list of values for that property\&.
.RE
.PP
\fBrecord\fR \fI boolean\fR
.RS 4
Default:
\fIyes\fR\&. Whether to ask the backup program to update its database (e\&.g\&.
/etc/dumpdates
for DUMP or
/usr/local/var/amanda/gnutar\-lists
for GNUTAR) of time stamps\&. This is normally enabled for daily backups and turned off for periodic archival runs\&.
.RE
.PP
\fBskip\-full\fR \fI boolean\fR
.RS 4
Default:
\fIno\fR\&. If
\fItrue\fR
and
\fBplanner\fR
has scheduled a full backup, these disks will be skipped, and full backups should be run off\-line on these days\&. It was reported that
\fIAmanda\fR
only schedules level 1 incrementals in this configuration; this is probably a bug\&.
.RE
.PP
\fBskip\-incr\fR \fI boolean\fR
.RS 4
Default:
\fIno\fR\&. If
\fItrue\fR
and
\fBplanner\fR
has scheduled an incremental backup, these disks will be skipped\&.
.RE
.PP
\fBssh_keys\fR \fI string\fR
.RS 4
Default:
\fINo default\fR\&. The key file the ssh auth will use, it must be the private key\&. If this parameter is not specified, then the default ssh key will be used\&.
.RE
.PP
\fBstarttime\fR \fI int\fR
.RS 4
Default:
\fInone\fR\&. Backups will not start until after this time of day\&. The value should be hh*100+mm, e\&.g\&. 6:30PM (18:30) would be entered as
1830\&.
.RE
.PP
\fBstrategy\fR \fI string\fR
.RS 4
Default:
\fIstandard\fR\&. Strategy to use when planning what level of backup to run next\&. Values are:
.PP
\fBstandard\fR
.RS 4
The standard
\fIAmanda\fR
schedule\&.
.RE
.PP
\fBnofull\fR
.RS 4
Never do full backups, only level 1 incrementals\&.
.RE
.PP
\fBnoinc\fR
.RS 4
Never do incremental backups, only full dumps\&.
.RE
.PP
\fBskip\fR
.RS 4
Never do backups (useful when sharing the
\fIdisklist\fR
file)\&.
.RE
.PP
\fBincronly\fR
.RS 4
Only do incremental dumps\&.
\fBamadmin force\fR
should be used to tell
\fIAmanda\fR
that a full dump has been performed off\-line, so that it resets to level 1\&.
.RE
.RE
.PP
\fBtape_splitsize\fR \fI int\fR
.RS 4
Default:
\fInone\fR\&. Split dump file on tape into pieces of a specified size\&. This allows dumps to be spread across multiple tapes, and can potentially make more efficient use of tape space\&. Note that if this value is too large (more than half the size of the average dump being split), substantial tape space can be wasted\&. If too small, large dumps will be split into innumerable tiny dumpfiles, adding to restoration complexity\&. A good rule of thumb, usually, is 1/10 of the size of your tape\&.
.sp
The default unit is Kbytes if it is not specified\&.
.RE
.PP
\fBsplit_diskbuffer\fR \fI string\fR
.RS 4
Default:
\fInone\fR\&. When dumping a split dump in PORT\-WRITE mode (usually meaning "no holding disk"), buffer the split chunks to a file in the directory specified by this option\&.
.RE
.PP
\fBfallback_splitsize\fR \fI int\fR
.RS 4
Default:
\fI10M\fR\&. When dumping a split dump in PORT\-WRITE mode, if no split_diskbuffer is specified (or if we somehow fail to use our split_diskbuffer), we must buffer split chunks in memory\&. This specifies the maximum size split chunks can be in this scenario, and thus the maximum amount of memory consumed for in\-memory splitting\&. The size of this buffer can be changed from its (very conservative) default to a value reflecting the amount of memory that each taper process on the dump server may reasonably consume\&.
.sp
The default unit is Kbytes if it is not specified\&.
.RE
.PP
The following
\fBdumptype\fR
entries are predefined by
\fIAmanda\fR:
.nf
define dumptype "no\-compress" {
    compress none
}
define dumptype "compress\-fast" {
    compress client fast
}
define dumptype "compress\-best" {
    compress client best
}
define dumptype "srvcompress" {
    compress server fast
}
define dumptype "bsd\-auth" {
    auth bsd
}
define dumptype "krb4\-auth" {
    auth krb4
}
define dumptype "no\-record" {
    record no
}
define dumptype "no\-hold" {
    holdingdisk no
}
define dumptype "no\-full" {
    skip\-full yes
} 
.fi
.PP
In addition to options in a
\fBdumptype\fR
section, one or more other
\fBdumptype\fR
names may be supplied as identifiers, which make this
\fBdumptype\fR
inherit options from other previously defined
\fBdumptype\fRs\&. For instance, two sections might be the same except for the
\fBrecord\fR
option:
.nf
define dumptype "normal" {
    comment "Normal backup, no compression, do indexing"
    no\-compress
    index yes
    maxdumps 2
}
define dumptype "testing" {
    comment "Test backup, no compression, do indexing, no recording"
    "normal"
    record no
}
.fi
.PP
\fIAmanda\fR
provides a
\fBdumptype\fR
named
\fIglobal\fR
in the sample
\fBamanda\&.conf\fR
file that all
\fBdumptype\fRs should reference\&. This provides an easy place to make changes that will affect every
\fBdumptype\fR\&.
.SH "TAPETYPE SECTION"
.PP
The
\fBamanda\&.conf\fR
file may define multiple types of tape media and devices\&. The information is entered in a
\fBtapetype\fR
section, which looks like this in the config file:
.nf
define tapetype "\fIname\fR" {
    \fItapetype\-option\fR \fItapetype\-value\fR
    \&.\&.\&.
}
.fi
.PP
\fIName\fR
is the name of this type of tape medium/device\&. It is referenced from the
\fBtapetype\fR
option in the main part of the config file\&.
.PP
The tapetype options and values are:
.PP
\fBcomment\fR \fI string\fR
.RS 4
Default:
\fInone\fR\&. A comment string describing this set of tape information\&.
.RE
.PP
\fBfilemark\fR \fI int\fR
.RS 4
Default:
\fI1 kbytes\fR\&. How large a file mark (tape mark) is, measured in kbytes\&. If the size is only known in some linear measurement (e\&.g\&. inches), convert it to kbytes using the device density\&.
.RE
.PP
\fBlength\fR \fI int\fR
.RS 4
Default:
\fI2000 kbytes\fR\&. How much data will fit on a tape, expressed in kbytes\&.
.sp
Note that this value is only used by
\fIAmanda\fR
to schedule which backups will be run\&. Once the backups start,
\fIAmanda\fR
will continue to write to a tape until it gets an error, regardless of what value is entered for
\fBlength\fR
(but see
\fBamanda-devices\fR(7)
for exceptions)\&.
.RE
.PP
\fBblocksize\fR \fI int\fR
.RS 4
Default:
\fI32 kbytes\fR\&. How much data will be written in each tape record, expressed in kbytes\&. This is similar to the
\fIBLOCK_SIZE\fR
device property, but if the blocksize is not a multiple of 1024 bytes, then this parameter cannot be used to specify it, and the property must be used instead\&.
.RE
.PP
\fBreadblocksize\fR \fI int\fR
.RS 4
Default:
\fI32 kytes\fR
How much data will be read in each tape record\&. This can be used to override a device\'s block size for reads only\&. This may be useful, for example, in reading a tape written with a 256k block size when Amanda is configured to use 128k blocks\&. This unusual feature is not supported by all operating systems and tape devices\&.
.sp
The default unit is Kbytes if it is not specified\&.
.RE
.PP
\fBspeed\fR \fI int\fR
.RS 4
Default:
\fI200 bps\fR\&. How fast the drive will accept data, in bytes per second\&. This parameter is NOT currently used by
\fIAmanda\fR\&.
.RE
.PP
\fBlbl\-templ\fR \fI string\fR
.RS 4
A PostScript template file used by
\fBamreport\fR
to generate labels\&. Several sample files are provided with the
\fIAmanda\fR
sources in the
\fIexample\fR
directory\&. See the
\fBamreport\fR(8)
man page for more information\&.
.RE
.PP
In addition to options, another
\fBtapetype\fR
name may be supplie as an identifier, which makes this
\fBtapetype\fR
inherit options from another
\fBtapetype\fR\&. For instance, the only difference between a DLT4000 tape drive using Compact\-III tapes and one using Compact\-IV tapes is the length of the tape\&. So they could be entered as:
.nf
define tapetype "DLT4000\-III" {
    comment "DLT4000 tape drives with Compact\-III tapes"
    length 12500 mbytes         # 10 Gig tapes with some compression
    filemark 2000 kbytes
    speed 1536 kps
}
define tapetype "DLT4000\-IV" {
    "DLT4000\-III"
    comment "DLT4000 tape drives with Compact\-IV tapes"
    length 25000 mbytes         # 20 Gig tapes with some compression
}
.fi
.SH "INTERFACE SECTION"
.PP
The
\fBamanda\&.conf\fR
file may define multiple types of network interfaces\&. The information is entered in an
\fBinterface\fR
section, which looks like this:
.nf
define interface "\fIname\fR" {
    \fIinterface\-option\fR \fIinterface\-value\fR
    \&.\&.\&.
}
.fi
.PP
\fIname\fR
is the name of this type of network interface\&. It is referenced from the
\fIdisklist\fR
file\&.
.PP
Note that these sections define network interface characteristics, not the actual interface that will be used\&. Nor do they impose limits on the bandwidth that will actually be taken up by
\fIAmanda\fR\&.
\fIAmanda\fR
computes the estimated bandwidth each file system backup will take based on the estimated size and time, then compares that plus any other running backups with the limit as another of the criteria when deciding whether to start the backup\&. Once a backup starts,
\fIAmanda\fR
will use as much of the network as it can leaving throttling up to the operating system and network hardware\&.
.PP
The interface options and values are:
.PP
\fBcomment\fR \fI string\fR
.RS 4
Default:
\fInone\fR\&. A comment string describing this set of network information\&.
.RE
.PP
\fBuse\fR \fI int\fR
.RS 4
Default:
\fI8000 Kbps\fR\&. The speed of the interface in Kbytes per second\&.
.RE
.PP
In addition to options, another
\fBinterface\fR
name may be supplied as an identifier, which makes this
\fBinterface\fR
inherit options from another
\fBinterface\fR\&. At the moment, this is of little use\&.
.SH "APPLICATION SECTION"
.PP
The
\fBamanda\&.conf\fR
file may define multiple types of application\&. The information is entered in a
\fBapplication\-tool\fR
section, which looks like this:
.nf
define application\-tool "\fIname\fR" {
    \fIapplication\-option\fR \fIapplication\-value\fR
    \&.\&.\&.
}
.fi
.PP
\fIname\fR
is the name of this type of application\&. It is referenced from the
\fIdumptype\fR
.PP
The application\-tool options and values are:
.PP
\fBcomment\fR \fIstring\fR
.RS 4
Default:
\fInone\fR\&. A comment string describing this application\&.
.RE
.PP
\fBplugin\fR \fIstring\fR
.RS 4
No default\&. Must be set to the name of the program\&. This program must be in the
\fI$libexecdir/amanda/application\fR
directory on the client\&.
.RE
.PP
\fBproperty\fR [append] [priority] \fIstring\fR \fIstring\fR+
.RS 4
No default\&. You can set property for the application, each application have a different set of property\&. Both strings are quoted; the first string contains the name of the property to set, and the others contains its values\&.
\fBappend\fR
keyword append the values to the list of values for that property\&.
\fBpriority\fR
keyword disallow the setting of that property on the client\&.
.RE
.SH "SCRIPT SECTION"
.PP
The
\fBamanda\&.conf\fR
file may define multiple types of script\&. The information is entered in a
\fBscript\-tool\fR
section, which looks like this:
.nf
define script\-tool "\fIname\fR" {
    \fIscript\-option\fR \fIscript\-value\fR
    \&.\&.\&.
}
.fi
.PP
\fIname\fR
is the name of this type of script\&. It is referenced from the
\fIdumptype\fR
.PP
The script\-tool options and values are:
.PP
\fBcomment\fR \fIstring\fR
.RS 4
Default:
\fInone\fR\&. A comment string describing this script\&.
.RE
.PP
\fBplugin\fR \fIstring\fR
.RS 4
No default\&. Must be set to the name of the program\&. This program must be in the
\fI$libexecdir/amanda/application\fR
directory on the client and/or server\&.
.RE
.PP
\fBexecute_where\fR [client|server]
.RS 4
Default:
\fIclient\fR\&. Where the script must be executed, on the client or server\&.
.RE
.PP
\fBexecute_on\fR \fIexecute_on\fR[,\fIexecute_on\fR]*
.RS 4
No default\&. When the script must be executed, you can specify many of them:
.PP
\fBpre\-dle\-amcheck\fR
.RS 4
Execute before the amcheck command for the dle\&.
.RE
.PP
\fBpre\-host\-amcheck\fR
.RS 4
Execute before the amcheck command for all dle for the client\&.
.RE
.PP
\fBpost\-dle\-amcheck\fR
.RS 4
Execute after the amcheck command for the dle\&.
.RE
.PP
\fBpost\-host\-amcheck\fR
.RS 4
Execute after the amcheck command for all dle for the client\&.
.RE
.PP
\fBpre\-dle\-estimate\fR
.RS 4
Execute before the estimate command for the dle\&.
.RE
.PP
\fBpre\-host\-estimate\fR
.RS 4
Execute before the estimate command for all dle for the client\&.
.RE
.PP
\fBpost\-dle\-estimate\fR
.RS 4
Execute after the estimate command for the dle\&.
.RE
.PP
\fBpost\-host\-estimate\fR
.RS 4
Execute after the estimate command for all dle for the client\&.
.RE
.PP
\fBpre\-dle\-backup\fR
.RS 4
Execute before the backup command for the dle\&.
.RE
.PP
\fBpre\-host\-backup\fR
.RS 4
Execute before the backup command for all dle for the client\&.
.RE
.PP
\fBpost\-dle\-backup\fR
.RS 4
Execute after the backup command for the dle\&.
.RE
.PP
\fBpost\-host\-backup\fR
.RS 4
Execute after the backup command for all dle for the client\&.
.RE
.PP
\fBpre\-recover\fR
.RS 4
Execute before any level is recovered\&.
.RE
.PP
\fBpost\-recover\fR
.RS 4
Execute after all levels are recovered\&.
.RE
.PP
\fBpre\-level\-recover\fR
.RS 4
Execute before each level recovery\&.
.RE
.PP
\fBpost\-level\-recover\fR
.RS 4
Execute after each level recovery\&.
.RE
.PP
\fBinter\-level\-recover\fR
.RS 4
Execute between two levels of recovery\&.
.RE
.sp
If you recover level 0 and 2 of the disk /usr with amrecover, it will execute:
.nf
script \-\-pre\-recover
script \-\-pre\-level\-recover \-\-level 0
#recovering level 0
script \-\-post\-level\-recover \-\-level 0
script \-\-inter\-level\-recover \-\-level 0 \-\-level 2
script \-\-pre\-level\-recover \-\-level 2
#recovering level 2
script \-\-post\-level\-recover \-\-level 2
script \-\-post\-recover
.fi
.RE
.PP
\fBproperty\fR [append] [priority] \fIstring\fR \fIstring\fR+
.RS 4
No default\&. You can set property for the script, each script have a different set of property\&. Both strings are quoted; the first string contains the name of the property to set, and the others contains its values\&.
\fBappend\fR
keyword append the values to the list of values for that property\&.
\fBpriority\fR
keyword disallow the setting of that property on the client\&.
.RE
.SH "DEVICE SECTION"
.PP
Backend storage devices are specified in
\fBamanda\&.conf\fR
in the form of "device" sections, which look like this:
.nf
define device \fIname\fR {
    commend "\fIcomment (optional)\fR"
    tapedev "\fIdevice\-specifier\fR"
    device_property "\fIprop\-name\fR" "\fIprop\-value\fR"
    \&.\&.\&.
}
.fi
.PP
\fIname\fR
is the user\-specified name of this device\&. It is referenced from the global
\fItapedev\fR
parameter\&. The
\fIdevice\-specifier\fR
specifies the device name to use; see
\fBamanda-devices\fR(7)\&. As with most sections, the
\fIcomment\fR
parmeter is optional and only for the user\'s convenience\&.
.PP
An arbitrary number of
\fIdevice_property\fR
parameters can be specified\&. Again, see
\fBamanda-devices\fR(7)
for information on device properties\&.
.SH "CHANGER SECTION"
.PP
Changers are described in
\fBamanda\&.conf\fR
in the form of "changer" sections, which look like this:
.nf
define changer \fIname\fR {
    comment "\fIcomment (optional)\fR"
    tapedev "\fItape\-device\fR"
    tpchanger "\fIchanger\-type\fR"
    changerdev "\fIdevice\-name\fR"
    changerfile "\fIstate\-file\fR"
    \&.\&.\&.
}
.fi
.PP
\fIname\fR
is the user\-specified name of this device\&. The remaining parameters are specific to the changer type selected\&.
.SH "SEE ALSO"
.PP

\fBamanda\fR(8),
\fBamanda-client.conf\fR(5),
\fBamcrypt\fR(8),
\fBaespipe\fR(1),
: http://wiki.zmanda.com
.SH "AUTHORS"
.PP
\fBJames da Silva\fR <\&jds@amanda\&.org\&>
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
