'\" t
.\"     Title: amanda-client.conf
.\"    Author: James da Silva <jds@amanda.org>
.\" Generator: DocBook XSL Stylesheets vsnapshot_8273 <http://docbook.sf.net/>
.\"      Date: 11/05/2009
.\"    Manual: File formats and conventions
.\"    Source: Amanda 2.6.1p2
.\"  Language: English
.\"
.TH "AMANDA\-CLIENT\&.CON" "5" "11/05/2009" "Amanda 2\&.6\&.1p2" "File formats and conventions"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amanda-client.conf \- Client configuration file for \fIAmanda\fR, the Advanced Maryland Automatic Network Disk Archiver
.SH "DESCRIPTION"
.PP
\fBamanda-client.conf\fR(5)
is the client configuration file for
\fIAmanda\fR\&. This manpage lists the relevant sections and parameters of this file for quick reference\&.
.PP
The files
\fB<CONFIG_DIR>/amanda\-client\&.conf\fR
and
\fB<CONFIG_DIR>/<config>/amanda\-client\&.conf\fR
are loaded\&.
.SH "SYNTAX"


The syntax of \fBamanda-client.conf\fR(5) is identical to that for
\fBamanda.conf\fR(5)\&.
.SH "GLOBAL PARAMETERS"
.PP
\fBconf\fR \fI string\fR
.RS 4
Default:
\fISet by configure\fR\&. The conf use by amrecover\&.
.RE
.PP
\fBclient_username\fR \fI string\fR
.RS 4
Default:
\fICLIENT_LOGIN\fR\&. Similar to the parameter of the same name in
\fBamanda.conf\fR(5), this specifies the username that
\fBamrecover\fR
should send when connecting to the server\&. It should match the username specified in
\&.amandahosts
on the server\&.
.RE
.PP
\fBindex_server\fR \fI string\fR
.RS 4
Default:
\fISet by configure\fR\&. The amindexd server amrecover will connect to\&.
.RE
.PP
\fBtape_server\fR \fI string\fR
.RS 4
Default:
\fISet by configure\fR\&. The amidxtaped server amrecover will connect to\&.
.RE
.PP
\fBtapedev\fR \fI string\fR
.RS 4
Default:
\fISet by configure\fR\&. The tapedev amrecover will use\&.
.RE
.PP
\fBauth\fR \fI string\fR
.RS 4
Default:
\fIbsd\fR\&. Type of authorization to perform between tape server and backup client hosts\&.
.sp
\fBbsd\fR, bsd authorization with udp initial connection and one tcp connection by data stream\&.
.sp
\fBbsdtcp\fR, bsd authorization but use only one tcp connection\&.
.sp
\fBbsdudp\fR, like bsd, but will use only one tcp connection for all data stream\&.
.sp
\fBkrb4\fR
to use Kerberos\-IV authorization\&.
.sp
\fBkrb5\fR
to use Kerberos\-V authorization\&.
.sp
\fBlocal\fR, if the client is the server, it doesn\'t require authencation setup\&.
.sp
\fBrsh\fR
to use rsh authorization\&.
.sp
\fBssh\fR
to use OpenSSH authorization\&.
.RE
.PP
\fBssh_keys\fR \fI string\fR
.RS 4
Default:
\fINo default\fR\&. The key file the ssh auth will use, it must be the private key\&. If this parameter is not specified, then the default ssh key will be used\&.
.RE
.PP
\fBgnutar_list_dir\fR \fI string\fR
.RS 4
Default from configure
\fI\-\-with\-gnutar\-listdir=DIR\fR\&. The directory where gnutar keep its state file\&.
.RE
.PP
\fBmailer\fR \fI string\fR
.RS 4
Default found by configure\&. A mail program that can send mail with \'\fIMAILER \-s "subject" user < message_file\fR\'\&.
.RE
.PP
\fBamandates\fR \fI string\fR
.RS 4
Default:
\fI/etc/amandates\fR\&. The file where amanda keep the last date of each dumplevel\&.
.RE
.PP
\fBconnect_tries\fR int
.RS 4
Default:
\fI3\fR\&. How many times the server will try a connection\&.
.RE
.PP
\fBrep_tries\fR int
.RS 4
Default:
\fI5\fR\&. How many times amandad will resend a REP packet if it doesn\'t get the ACK packet\&.
.RE
.PP
\fBdebug_amandad\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the amandad process
.RE
.PP
\fBdebug_amidxtaped\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the amidxtaped process
.RE
.PP
\fBdebug_amindexd\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the amindexd process
.RE
.PP
\fBdebug_amrecover\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the amrecover process
.RE
.PP
\fBdebug_auth\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the auth module
.RE
.PP
\fBdebug_event\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the event module
.RE
.PP
\fBdebug_holding\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the holdingdisk module
.RE
.PP
\fBdebug_protocol\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the protocol module
.RE
.PP
\fBdebug_selfcheck\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the selfcheck process
.RE
.PP
\fBdebug_sendsize\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the sendsize process
.RE
.PP
\fBdebug_sendbackup\fR int
.RS 4
Default:
\fI0\fR\&. Debug level of the sendbackup process
.RE
.PP
\fBreserved\-udp\-port\fR int,int
.RS 4
Default: \-\-with\-udpportrange or
\fI512,1023\fR\&. Reserved udp port that will be used (amrecover with bsd or bsdudp)
.RE
.PP
\fBreserved\-tcp\-port\fR int,int
.RS 4
Default: \-\-with\-low\-tcpportrange or
\fI512,1023\fR\&. Reserved tcp port that will be used (amrecover with bsdtcp)
.RE
.PP
\fBunreserved\-tcp\-port\fR int,int
.RS 4
Default: \-\-with\-tcpportrange or
\fI1025,65536\fR\&. Unreserved tcp port that will be used (bsd, bsdudp)
.RE
.PP
\fBproperty\fR "name" "value"
.RS 4
Adds a global property for this client host, useful for e\&.g\&., Application API plugins\&.
.RE
.SH "APPLICATION SECTION"
.PP
The
\fBamanda\&.conf\fR
file may define multiple types of application\&. The information is entered in a
\fBapplication\-tool\fR
section, which looks like this:
.nf
define application\-tool "\fIname\fR" {
    \fIapplication\-option\fR \fIappli
cation\-value\fR
    \&.\&.\&.
}
.fi
.PP
\fIname\fR
is the name of this type of application\&. It is referenced from the
\fIdumptype\fR
.PP
The application\-tool options and values are:
.PP
\fBcomment\fR \fIstring\fR
.RS 4
Default:
\fInone\fR\&. A comment string describing this application\&.
.RE
.PP
\fBplugin\fR \fIstring\fR
.RS 4
No default\&. Must be set to the name of the program\&. This program must be in the
\fI$libexecdir/amanda/application\fR
directory on the client\&.
.RE
.PP
\fBproperty\fR [append] [priority] \fIstring\fR \fIstring\fR+
.RS 4
No default\&. You can set property for the application, each application have a different set of property\&. Both strings are quoted; the first string contains the name of the property to set, and the others contains its values\&.
\fBappend\fR
keyword append the values to the list of values for that property\&.
\fBpriority\fR
keyword disallow the setting of that property on the server\&.
.RE
.SH "SCRIPT SECTION"
.PP
The
\fBamanda\&.conf\fR
file may define multiple types of script\&. The information is entered in a
\fBscript\-tool\fR
section, which looks like this:
.nf
define script\-tool "\fIname\fR" {
    \fIscript\-option\fR \fIscript\-value\fR
    \&.\&.\&.
}
.fi
.PP
\fIname\fR
is the name of this type of script\&. It is referenced from the
\fIdumptype\fR
.PP
The script\-tool options and values are:
.PP
\fBcomment\fR \fIstring\fR
.RS 4
Default:
\fInone\fR\&. A comment string describing this script\&.
.RE
.PP
\fBplugin\fR \fIstring\fR
.RS 4
No default\&. Must be set to the name of the program\&. This program must be in the
\fI$libdir/amanda/application\fR
directory on the client and/or server\&.
.RE
.PP
\fBexecute_where\fR [client|server]
.RS 4
Default:
\fIclient\fR\&. Where the script must be executed, on the client or server\&. Only
\fIclient\fR
is valid\&.
.RE
.PP
\fBexecute_on\fR \fIexecute_on\fR[,\fIexecute_on\fR]*
.RS 4
No default\&. When the script must be executed, you can specify many of them:
.PP
\fBpre\-dle\-amcheck\fR
.RS 4
Execute before the amcheck command for the dle\&.
.RE
.PP
\fBpre\-host\-amcheck\fR
.RS 4
Execute before the amcheck command for all dle for the client\&.
.RE
.PP
\fBpost\-dle\-amcheck\fR
.RS 4
Execute after the amcheck command for the dle\&.
.RE
.PP
\fBpost\-host\-amcheck\fR
.RS 4
Execute after the amcheck command for all dle for the client\&.
.RE
.PP
\fBpre\-dle\-estimate\fR
.RS 4
Execute before the estimate command for the dle\&.
.RE
.PP
\fBpre\-host\-estimate\fR
.RS 4
Execute before the estimate command for all dle for the client\&.
.RE
.PP
\fBpost\-dle\-estimate\fR
.RS 4
Execute after the estimate command for the dle\&.
.RE
.PP
\fBpost\-host\-estimate\fR
.RS 4
Execute after the estimate command for all dle for the client\&.
.RE
.PP
\fBpre\-dle\-backup\fR
.RS 4
Execute before the backup command for the dle\&.
.RE
.PP
\fBpre\-host\-backup\fR
.RS 4
Execute before the backup command for all dle for the client\&.
.RE
.PP
\fBpost\-dle\-backup\fR
.RS 4
Execute after the backup command for the dle\&.
.RE
.PP
\fBpost\-host\-backup\fR
.RS 4
Execute after the backup command for all dle for the client\&.
.RE
.PP
\fBpre\-recover\fR
.RS 4
Execute before any level is recovered\&.
.RE
.PP
\fBpost\-recover\fR
.RS 4
Execute after all levels are recovered\&.
.RE
.PP
\fBpre\-level\-recover\fR
.RS 4
Execute before each level recovery\&.
.RE
.PP
\fBpost\-level\-recover\fR
.RS 4
Execute after each level recovery\&.
.RE
.PP
\fBinter\-level\-recover\fR
.RS 4
Execute between two levels of recovery\&.
.RE
.RE
.PP
\fBproperty\fR [append] [priority] \fIstring\fR \fIstring\fR+
.RS 4
No default\&. You can set property for the script, each script have a different set of property\&. Both strings are quoted; the first string contains the name of the property to set, and the others contains its values\&.
\fBappend\fR
keyword append the values to the list of values for that property\&.
\fBpriority\fR
keyword disallow the setting of that property on the server\&.
.RE
.SH "SEE ALSO"
.PP

\fBamanda\fR(8),
\fBamanda.conf\fR(5),
\fBamcrypt\fR(8),
\fBaespipe\fR(1),
: http://wiki.zmanda.com
.SH "AUTHORS"
.PP
\fBJames da Silva\fR <\&jds@amanda\&.org\&>
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
