.\"     Title: amanda-client.conf
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 08/22/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "AMANDA\-CLIENT\.CONF" "5" "08/22/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
amanda-client.conf - Client configuration file for Amanda, the Advanced Maryland Automatic Network Disk Archiver
.SH "DESCRIPTION"
.PP
\fIamanda\-client\.conf\fR
is the client configuration file for
\fIAmanda\fR\. This manpage lists the relevant sections and parameters of this file for quick reference\.
.PP
The files
\fB<CONFIG_DIR>/amanda\-client\.conf\fR
and
\fB<CONFIG_DIR>/<config>/amanda\-client\.conf\fR
are loaded\.
.SH "PARAMETERS"
.PP
There are a number of configuration parameters that control the behavior of the
\fIAmanda\fR
programs\. All have default values, so you need not specify the parameter in
\fBamanda\-client\.conf\fR
if the default is suitable\.
.PP
Lines starting with # are ignored, as are blank lines\. Comments may be placed on a line with a directive by starting the comment with a #\. The remainder of the line is ignored\.
.PP
Keywords are case insensitive, i\.e\.
\fBauth\fR
and
\fBAuth\fR
are treated the same\.
.PP
Integer arguments may have one of the following (case insensitive) suffixes, some of which have a multiplier effect:
.SS "POSSIBLE SUFFIXES"
.PP
\fBb byte bytes\fR
.RS 4
Some number of bytes\.
.RE
.PP
\fBbps\fR
.RS 4
Some number of bytes per second\.
.RE
.PP
\fBk kb kbyte kbytes kilobyte kilobytes\fR
.RS 4
Some number of kilobytes (bytes*1024)\.
.RE
.PP
\fBkps kbps\fR
.RS 4
Some number of kilobytes per second (bytes*1024)\.
.RE
.PP
\fBm mb meg mbyte mbytes megabyte megabytes\fR
.RS 4
Some number of megabytes (bytes*1024*1024)\.
.RE
.PP
\fBmps mbps\fR
.RS 4
Some number of megabytes per second (bytes*1024*1024)\.
.RE
.PP
\fBg gb gbyte gbytes gigabyte gigabytes\fR
.RS 4
Some number of gigabytes (bytes*1024*1024*1024)\.
.RE
.PP
\fBtape tapes\fR
.RS 4
Some number of tapes\.
.RE
.PP
\fBday days\fR
.RS 4
Some number of days\.
.RE
.PP
\fBweek weeks\fR
.RS 4
Some number of weeks (days*7)\.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
The value
\fBinf\fR
may be used in most places where an integer is expected to mean an infinite amount\.
.sp
Boolean arguments may have any of the values
\fBy\fR,
\fByes\fR,
\fBt\fR,
\fBtrue\fR
or
\fBon\fR
to indicate a true state, or
\fBn\fR,
\fBno\fR,
\fBf\fR,
\fBfalse\fR
or
\fBoff\fR
to indicate a false state\. If no argument is given,
\fBtrue\fR
is assumed\.
.RE
.SS "PARAMETERS"
.PP
\fBconf\fR \fI string\fR
.RS 4
Default:
\fISet by configure\fR\. The conf use by amrecover\.
.RE
.PP
\fBindex_server\fR \fI string\fR
.RS 4
Default:
\fISet by configure\fR\. The amindexd server amrecover will connect to\.
.RE
.PP
\fBtape_server\fR \fI string\fR
.RS 4
Default:
\fISet by configure\fR\. The amidxtaped server amrecover will connect to\.
.RE
.PP
\fBtapedev\fR \fI string\fR
.RS 4
Default:
\fISet by configure\fR\. The tapedev amrecover will use\.
.RE
.PP
\fBauth\fR \fI string\fR
.RS 4
Default:
\fIbsd\fR\. Type of authorization to perform between tape server and backup client hosts\.
.sp
\fBbsd\fR, bsd authorization with udp initial connection and one tcp connection by data stream\.
.sp
\fBbsdtcp\fR, bsd authorization but use only one tcp connection\.
.sp
\fBbsdudp\fR, like bsd, but will use only one tcp connection for all data stream\.
.sp
\fBkrb4\fR
to use Kerberos\-IV authorization\.
.sp
\fBkrb5\fR
to use Kerberos\-V authorization\.
.sp
\fBlocal\fR, if the client is the server, it doesn\'t require authencation setup\.
.sp
\fBrsh\fR
to use rsh authorization\.
.sp
\fBssh\fR
to use OpenSSH authorization\.
.RE
.PP
\fBssh_keys\fR \fI string\fR
.RS 4
Default:
\fINo default\fR\. The key file the ssh auth will use, it must be the private key\. If this parameter is not specified, then the deafult ssh key will be used\.
.RE
.PP
\fBgnutar_list_dir\fR \fI string\fR
.RS 4
Default from configure
\fI\-\-with\-gnutar\-listdir=DIR\fR\. The directory where gnutar keep its state file\.
.RE
.PP
\fBamandates\fR \fI string\fR
.RS 4
Default:
\fI/etc/amandates\fR\. The file where amanda keep the last date of each dumplevel\.
.RE
.PP
\fBconnect_tries\fR int
.RS 4
Default:
\fI3\fR\. How many times the server will try a connection\.
.RE
.PP
\fBrep_tries\fR int
.RS 4
Default:
\fI5\fR\. How many times amandad will resend a REP packet if it doesn\'t get the ACK packet\.
.RE
.PP
\fBdebug_amandad\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the amandad process
.RE
.PP
\fBdebug_amidxtaped\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the amidxtaped process
.RE
.PP
\fBdebug_amindexd\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the amindexd process
.RE
.PP
\fBdebug_amrecover\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the amrecover process
.RE
.PP
\fBdebug_auth\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the auth module
.RE
.PP
\fBdebug_event\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the event module
.RE
.PP
\fBdebug_holding\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the holdingdisk module
.RE
.PP
\fBdebug_protocol\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the protocol module
.RE
.PP
\fBdebug_selfcheck\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the selfcheck process
.RE
.PP
\fBdebug_sendsize\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the sendsize process
.RE
.PP
\fBdebug_sendbackup\fR int
.RS 4
Default:
\fI0\fR\. Debug level of the sendbackup process
.RE
.PP
\fBreserved\-udp\-port\fR int,int
.RS 4
Default: \-\-with\-udpportrange or
\fI512,1023\fR\. Reserved udp port that will be used (amrecover with bsd or bsdudp)
.RE
.PP
\fBreserved\-tcp\-port\fR int,int
.RS 4
Default: \-\-with\-low\-tcpportrange or
\fI512,1023\fR\. Reserved tcp port that will be used (amrecover with bsdtcp)
.RE
.PP
\fBunreserved\-tcp\-port\fR int,int
.RS 4
Default: \-\-with\-tcpportrange or
\fI1025,65536\fR\. Unreserved tcp port that will be used (bsd, bsdudp)
.RE
.SH "AUTHOR"
.PP
James da Silva,
<jds@amanda\.org>: Original text
.PP
Stefan G\. Weichinger,
<sgw@amanda\.org>, maintainer of the
\fIAmanda\fR\-documentation: XML\-conversion, major update, splitting
.SH "SEE ALSO"
.PP

\fBamanda\fR(8),
\fBamanda.conf\fR(5),
\fBamcrypt\fR(8),
\fBaespipe\fR(1),
: http://wiki.zmanda.com
