.\"     Title: amcleanup
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "AMCLEANUP" "8" "05/14/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
amcleanup - run the Amanda cleanup process after a failure
.SH "SYNOPSIS"
.HP 10
\fBamcleanup\fR [\fB\-k\fR] [\fB\-v\fR] \fIconfig\fR
.SH "DESCRIPTION"
.PP
\fBAmcleanup\fR
generates the
\fI\fIAmanda\fR\fR\fI Mail Report\fR
and updates the
\fIAmanda\fR
databases after a system failure on a tape server host\. This cleanup process is normally done automatically as part of the
\fBamdump\fR
program, but if
\fBamdump\fR
cannot complete for some reason (usually because of a tape server host crash),
\fBamcleanup\fR
must be run some time later (usually during system boot)\.
.PP
See the
\fBamanda\fR(8)
man page for more details about
\fIAmanda\fR\.
.SH "OPTIONS"
.PP
\fB\-k\fR
.RS 4
Kill all Amanda processes\.
.RE
.PP
\fB\-v\fR
.RS 4
Generate verbose output\.
.RE
.SH "EXAMPLES"
.PP
This example runs the
\fIAmanda\fR
cleanup process by hand after a failure\.
.sp
.RS 4
.nf
% amcleanup daily
.fi
.RE
.PP
Putting the following line in a system boot script (e\.g\.
\fI/etc/rc\.local\fR) runs the
\fIAmanda\fR
cleanup process as part of the reboot, eliminating the need to run it by hand\.
.sp
.RS 4
.nf
/usr/local/sbin/amcleanup daily
.fi
.RE
.PP
If nothing needs to be done,
\fBamcleanup\fR
exits normally with the message:
.sp
.RS 4
.nf
amcleanup: no unprocessed logfile to clean up\.
.fi
.RE
.SH "AUTHOR"
.PP
James da Silva,
<jds@amanda\.org>: Original text
.PP
Stefan G\. Weichinger,
<sgw@amanda\.org>, maintainer of the
\fIAmanda\fR\-documentation: XML\-conversion
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamdump\fR(8),
\fI\%http://wiki.zmanda.com\fR
