.\"     Title: amcrypt-ossl-asym
.\"    Author: Kevin Till <kevin.till@zmanda.com>
.\" Generator: DocBook XSL Stylesheets v1.74.0 <http://docbook.sf.net/>
.\"      Date: 01/22/2009
.\"    Manual: System Administration Commands
.\"    Source: Amanda 2.6.1
.\"  Language: English
.\"
.TH "AMCRYPT\-OSSL\-ASYM" "8" "01/22/2009" "Amanda 2\&.6\&.1" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * (re)Define some macros
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" toupper - uppercase a string (locale-aware)
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de toupper
.tr aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ
\\$*
.tr aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SH-xref - format a cross-reference to an SH section
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de SH-xref
.ie n \{\
.\}
.toupper \\$*
.el \{\
\\$*
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SH - level-one heading that works better for non-TTY output
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de1 SH
.\" put an extra blank line of space above the head in non-TTY output
.if t \{\
.sp 1
.\}
.sp \\n[PD]u
.nr an-level 1
.set-an-margin
.nr an-prevailing-indent \\n[IN]
.fi
.in \\n[an-margin]u
.ti 0
.HTML-TAG ".NH \\n[an-level]"
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
\." make the size of the head bigger
.ps +3
.ft B
.ne (2v + 1u)
.ie n \{\
.\" if n (TTY output), use uppercase
.toupper \\$*
.\}
.el \{\
.nr an-break-flag 0
.\" if not n (not TTY), use normal case (not uppercase)
\\$1
.in \\n[an-margin]u
.ti 0
.\" if not n (not TTY), put a border/line under subheading
.sp -.6
\l'\n(.lu'
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" SS - level-two heading that works better for non-TTY output
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de1 SS
.sp \\n[PD]u
.nr an-level 1
.set-an-margin
.nr an-prevailing-indent \\n[IN]
.fi
.in \\n[IN]u
.ti \\n[SN]u
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.ps \\n[PS-SS]u
\." make the size of the head bigger
.ps +2
.ft B
.ne (2v + 1u)
.if \\n[.$] \&\\$*
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" BB/BE - put background/screen (filled box) around block of text
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de BB
.if t \{\
.sp -.5
.br
.in +2n
.ll -2n
.gcolor red
.di BX
.\}
..
.de EB
.if t \{\
.if "\\$2"adjust-for-leading-newline" \{\
.sp -1
.\}
.br
.di
.in
.ll
.gcolor
.nr BW \\n(.lu-\\n(.i
.nr BH \\n(dn+.5v
.ne \\n(BHu+.5v
.ie "\\$2"adjust-for-leading-newline" \{\
\M[\\$1]\h'1n'\v'+.5v'\D'P \\n(BWu 0 0 \\n(BHu -\\n(BWu 0 0 -\\n(BHu'\M[]
.\}
.el \{\
\M[\\$1]\h'1n'\v'-.5v'\D'P \\n(BWu 0 0 \\n(BHu -\\n(BWu 0 0 -\\n(BHu'\M[]
.\}
.in 0
.sp -.5v
.nf
.BX
.in
.sp .5v
.fi
.\}
..
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" BM/EM - put colored marker in margin next to block of text
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.de BM
.if t \{\
.br
.ll -2n
.gcolor red
.di BX
.\}
..
.de EM
.if t \{\
.br
.di
.ll
.gcolor
.nr BH \\n(dn
.ne \\n(BHu
\M[\\$1]\D'P -.75n 0 0 \\n(BHu -(\\n[.i]u - \\n(INu - .75n) 0 0 -\\n(BHu'\M[]
.in 0
.nf
.BX
.in
.fi
.\}
..
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "Name"
amcrypt-ossl-asym \- crypt program for \fIAmanda\fR asymmetric data encryption using OpenSSL
.SH "Synopsis"
.fam C
.HP \w'\fBamcrypt\-ossl\-asym\fR\ 'u
\fBamcrypt\-ossl\-asym\fR [\-d]
.fam
.SH "DESCRIPTION"
.PP

\fBamcrypt\-ossl\-asym\fR
uses
\fBOpenSSL\fR
to encrypt and decrypt data\&. OpenSSL is available from
www\&.openssl\&.org\&. OpenSSL offers a wide variety of cipher choices (
\fBamcrypt\-ossl\-asym\fR
defaults to 256\-bit AES) and can use hardware cryptographic accelerators on several platforms\&.
.PP

\fBamcrypt\-ossl\-asym\fR
will search for the OpenSSL program in the following directories: /bin:/usr/bin:/usr/local/bin:/usr/ssl/bin:/usr/local/ssl/bin\&.
.SH "GENERATING PUBLIC AND PRIVATE KEYS"
.PP
RSA keys can be generated with the standard OpenSSL commands, e\&.g\&.:
.nf
$ cd /var/lib/amanda
$ openssl genrsa \-aes128 \-out backup\-privkey\&.pem 1024
Generating RSA private key, 1024 bit long modulus
[\&.\&.\&.]
Enter pass phrase for backup\-privkey\&.pem: \fIENTER YOUR PASS PHRASE\fR
Verifying \- Enter pass phrase for backup\-key\&.pem: \fIENTER YOUR PASS PHRASE\fR

$ openssl rsa \-in backup\-privkey\&.pem \-pubout \-out backup\-pubkey\&.pem
Enter pass phrase for backup\-privkey\&.pem: \fIENTER YOUR PASS PHRASE\fR
Writing RSA key
.fi
.PP
To generate a private key without a passphrase, omit the
\fB\-aes128\fR
option\&. See
\fBopenssl_genrsa\fR(1)
for more key generation options\&.
.PP
Note that it is always possible to generate the public key from the private key\&.
.SH "KEY AND PASSPHRASE MANAGEMENT"
.PP

\fBamcrypt\-ossl\-asym\fR
uses the
\fIpublic key\fR
to encrypt data\&. The security of the data does not depend on the confidentiality of the public key\&. The
\fIprivate key\fR
is used to decrypt data, and must be protected\&. Encrypted backup data cannot be recovered without the private key\&. The private key may optionally be encrypted with a passphrase\&.
.PP
While the public key must be online at all times to perorm backups, the private key and optional passphrase are only needed to restore data\&. It is recommended that the latter be stored offline all other times\&. For example, you could keep the private key on removable media, and copy it into place for a restore; or you could keep the private key online, encrypted with a passphrase that is present only for a restore\&.
.PP
OpenSSL\'s key derivation routines use a salt to guard against dictionary attacks on the pass phrase; still it is important to pick a pass phrase that is hard to guess\&. The Diceware method (see
www\&.diceware\&.com) can be used to create passphrases that are difficult to guess and easy to remember\&.
.SH "FILES"
.PP
/var/lib/amanda/backup\-privkey\&.pem
.RS 4
File containing the RSA private key\&. It should not be readable by any user other than the
\fIAmanda\fR
user\&.
.RE
.PP
/var/lib/amanda/backup\-pubkey\&.pem
.RS 4
File containing the RSA public key\&.
.RE
.PP
/var/lib/amanda/\&.am_passphrase
.RS 4
File containing the passphrase\&. It should not be readable by any user other than the
\fIAmanda\fR
user\&.
.RE
.SH "SEE ALSO"
.PP

\fBamanda\fR(8),
\fBamanda.conf\fR(5),
\fBopenssl\fR(1),
\fBamcrypt-ossl\fR(8),
: http://wiki.zmanda.com
.SH "Author"
.PP
\fBKevin Till\fR <\&kevin\&.till@zmanda\&.com\&>
.RS 4
Zmanda, Inc\&. (\FChttp://www\&.zmanda\&.com\F[])
.RE
.SH "Notes"
.IP " 1." 4
www.openssl.org
.RS 4
\%http://www.openssl.org/
.RE
.IP " 2." 4
www.diceware.com
.RS 4
\%http://www.diceware.com/
.RE
