.\"     Title: ammt
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 03/31/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "AMMT" "8" "03/31/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
ammt - Amanda version of mt
.SH "SYNOPSIS"
.HP 5
\fBammt\fR [\-d] [\-f | \-t | \fIdevice\fR] \fIcommand\fR [\fIcount\fR]
.SH "DESCRIPTION"
.PP
\fBAmmt\fR
provides just enough of the standard UNIX
\fBmt\fR
command for the needs of
\fIAmanda\fR\. This is handy when doing a full restore and the standard
\fBmt\fR
program has not yet been found\.
.PP
\fBAmmt\fR
also provides access to the
\fIAmanda\fR
output drivers that support various tape simulations\.
.PP
See the
\fBamanda\fR(8)
man page for more details about
\fIAmanda\fR\. See the
\fBOUTPUT DRIVERS\fR
section of
\fIamanda(8)\fR
for more information on the
\fIAmanda\fR
output drivers\.
.SH "OPTIONS"
.PP
\fB\-d\fR
.RS 4
Turn on debugging output\.
.RE
.PP
\fB\-f\fR\fI device\fR
.RS 4
Access tape device
\fIdevice\fR\. If not specified, the
\fBTAPE\fR
environment variable is used\.
.RE
.PP
\fB\-t\fR\fI device\fR
.RS 4
Same as
\fB\-f\fR\.
.RE
.PP
\fBcommand\fR\fI count\fR
.RS 4
Which command to issue, and an optional count of operations\.
.RE
.SH "COMMANDS"
.PP
Each command may be abbreviated to whatever length makes it unique\.
.PP
\fBeof|weof\fR\fI count\fR
.RS 4
Write
\fIcount\fR
(default: 1) end of file marks (tapemarks)\.
.RE
.PP
\fBfsf\fR\fI count\fR
.RS 4
Skip forward
\fIcount\fR
(default: 1) files\.
.RE
.PP
\fBbsf\fR\fI count\fR
.RS 4
Skip backward
\fIcount\fR
(default: 1) files\.
.RE
.PP
\fBasf\fR\fI count\fR
.RS 4
Position to file number
\fIcount\fR
(default: 0) where zero is beginning of tape\. This is the same as a
\fBrewind\fR
followed by a
\fBfsf\fR
\fIcount\fR\.
.RE
.PP
\fBrewind\fR
.RS 4
Rewind to beginning of tape\.
.RE
.PP
\fBoffline|rewoffl\fR
.RS 4
Rewind to beginning of tape and unload the tape from the drive\.
.RE
.PP
\fBstatus\fR
.RS 4
Report status information about the drive\. Which data reported, and what it means, depends on the underlying operating system, and may include:
.PP
ONLINE
.RS 4
Indicates the drive is online and ready\.
.RE
.PP
OFFLINE
.RS 4
Indicates the drive is offline or not ready\.
.RE
.PP
BOT
.RS 4
Indicates the drive is at beginning of tape\.
.RE
.PP
EOT
.RS 4
Indicates the drive is at end of tape\.
.RE
.PP
PROTECTED
.RS 4
Indicates the tape is write protected\.
.RE
.PP
ds
.RS 4
Device status\.
.RE
.PP
er
.RS 4
Error register\.
.RE
.PP
fileno
.RS 4
Current tape file number\.
.RE
.PP
blkno
.RS 4
Current tape block number file\.
.RE
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
Many systems only report good data when a tape is in the drive and ready\.
.SH "AUTHOR"
.PP
Marc Mengel
<mengel@fnal\.gov>, John R\. Jackson
<jrj@purdue\.edu>: Original text
.PP
Stefan G\. Weichinger,
<sgw@amanda\.org>, maintainer of the
\fIAmanda\fR\-documentation: XML\-conversion
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBhttp://wiki.zmanda.com\fR()
