'\" t
.\"     Title: amreport
.\"    Author: Stefan G. Weichinger <sgw@amanda.org>
.\" Generator: DocBook XSL Stylesheets vsnapshot_8273 <http://docbook.sf.net/>
.\"      Date: 06/01/2010
.\"    Manual: System Administration Commands
.\"    Source: Amanda 3.1.0
.\"  Language: English
.\"
.TH "AMREPORT" "8" "06/01/2010" "Amanda 3\&.1\&.0" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amreport \- generate a formatted output of statistics for an Amanda run
.SH "SYNOPSIS"
.HP \w'\fBamreport\fR\ 'u
\fBamreport\fR [\fIconfig\fR] [{\fB\-o\fR\ \fIconfigoption\fR}...] [(1)\ \fIcommand\-line options\fR | (2)\ \fIscript options\fR]
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.HP \w'(1)\ 'u
(1)\ [\-\-log=\fIlogfile\fR] [\-\-ps=\fIfilename\fR] [\-\-text=\fIfilename\fR] [\-\-xml=\fIfilename\fR] [\-\-print=\fIprinter\fR] [\-\-mail\-text=\fIrecipient\fR]
.HP \w'(2)\ 'u
(2)\ [\-i] [\-M\ \fIaddress\fR] [\-l\ \fIlogfile\fR] [\-f\ \fIoutputfile\fR] [\-p\ \fIpostscriptfile\fR] [\-\-from\-amdump]
.SH "DESCRIPTION"
.PP
\fBAmreport\fR
generates a summary report of an Amanda backup run\&.
.PP
See the
\fBamanda\fR(8)
man page for more details about Amanda\&.
.SH "OPTIONS"
.PP
\fIconfig\fR
.RS 4
Name of the configuration to process\&. If no configuration name is specified, amanda\&.conf is read from the current directory\&.
.RE
.PP
\fB\-o \fR\fB\fIconfigoption\fR\fR
.RS 4
See the "CONFIGURATION OVERRIDE" section in
\fBamanda\fR(8)\&.
.RE
.PP
Amreport operates in two distinct modes\&. Command\-line mode is intended for use by an administrator from the command line, and uses long command\-line options for clarity\&. Script mode is intended for use from scripts such as amdump, and has a lot of non\-obvious default behaviors to suit that need\&.
.PP
Unless a script\-mode option is given, amreport defaults to command\-line mode\&. If no options are given, amreport writes a report for the most recent logfile to stdout\&.
.SS "Command\-Line Mode Options"
.PP
\fB\-\-log=\fR\fB\fIlogfile\fR\fR
.RS 4
Use this logfile as the basis for the report\&. If this option is given, then the report is a "historical" report and will not include current state from e\&.g\&., holding disk and curinfo\&. If this option is not specified, then the most recent logfile will be used\&.
.RE
.PP
\fB\-\-ps=\fR\fB\fIfilename\fR\fR
.RS 4
Write a postscript label to
\fIfilename\fR\&. See "LABEL PRINTING" below\&. If filename is not specified, then the label is written to stdout\&.
.RE
.PP
\fB\-\-text=\fR\fB\fIfilename\fR\fR
.RS 4
Write a human\-readable text report to
\fIfilename\fR\&. If filename is not specified, then the report is written to stdout\&.
.RE
.PP
\fB\-\-xml=\fR\fB\fIfilename\fR\fR
.RS 4
Write an XML\-formatted report to
\fIfilename\fR\&. If filename is not specified, then the report is written to stdout\&.
.RE
.PP
\fB\-\-print=\fR\fB\fIprinter\fR\fR
.RS 4
Pipe a postscript label to
\fBlp\fR
or
\fBlpr\fR, specifying the given
\fIprinter\fR\&. If the printer is not specified, uses the default from the Amanda configuration, or the system default printer\&.
.RE
.PP
\fB\-\-mail\-text=\fR\fB\fIrecipient\fR\fR
.RS 4
Send a human\-readable text report to the given
\fIrecipient\fR
via the mailer specified in the Amanda configuration\&. If the recipient is not specified, this uses the
\fImailto\fR
from the Amanda configuration\&.
.RE
.SS "Script Mode Options"
.PP
\fB\-i\fR
.RS 4
Don\'t email the report\&.
.RE
.PP
\fB\-M\fR \fIaddress\fR
.RS 4
Mail the report to
\fIaddress\fR
instead of the
\fBmailto\fR
value from
\fIamanda\&.conf\fR\&.
.RE
.PP
\fB\-l\fR \fIlogfile\fR
.RS 4
Name of the log file to parse to generate the report\&. If a log file is not specified, it defaults to the file
$logdir/log, where
$logdir
is the log directory defined in amanda\&.conf\&.
.RE
.PP
\fB\-f\fR \fIoutputfile\fR
.RS 4
Normally,
\fBamreport\fR
sends the report via e\-mail to the
\fImailto\fR
user as defined in the amanda\&.conf file\&. If
\fIoutputfile\fR
is specified, then the report is put in
\fIoutputfile\fR\&.
.RE
.PP
\fB\-p\fR \fIpostscriptfile\fR
.RS 4
Send the postscript output to the file
\fIpostscriptfile\fR
instead of to the
\fBlpr\fR(1)
command\&. This option has an effect only if the
\fIlbl\-templ\fR
directive is specified in amanda\&.conf\&.
.RE
.PP
\fB\-\-from\-amdump\fR
.RS 4
Force script mode\&. Has no other effect\&.
.RE
.SH "LABEL PRINTING"
.PP
Amanda can print postscript labels describing the contents of tape(s) written in a run\&. The labels are designed to be folded and inserted into the tape case along with the tape or hole punched and put in a 3\-ring binder\&. Various label templates are provided to format data for different tape sizes\&.
.PP
The information printed varies slightly between label templates due to size constraints\&. Labels contain one line for each host/file\-system pair and may also contain the file number on the tape, the level of the dump, the original size of the dump and the size of the (possibly compressed) tape file\&.
.PP
Add the
\fIlbl\-templ\fR
parameter to the tapetype definition in amanda\&.conf to enable labels\&. If you don\'t add this line to your tapetype definition,
\fBamreport\fR
will not print tape labels\&.
.PP
You may use the
\fIprinter\fR
keyword in amanda\&.conf to print to other than the system default printer\&.
.SH "TEMPLATES"
.PP
Amanda provides label templates for the following tape types\&. These are pretty generic labels and should be easy to customize for other tape types or particular site needs\&.
.sp
.if n \{\
.RS 4
.\}
.nf
* ExaByte 8mm tapes
* DAT 4mm tapes
* DLT tapes
* 3\-ring binder
.fi
.if n \{\
.RE
.\}
.PP
The 3\-ring binder type is the most generic\&. It may be used to make a hardcopy log of the tapes\&.
.SH "EXIT CODE"

The exit code of \fBamreport\fR is the ORed value of:
.nf
 0  = success
 1  = error
 2  = a dle give strange message
 4  = a dle failed
 8  = Don\'t know the status of a dle (RESULT_MISSING in the report)
 16 = tape error or no more tape
.fi
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamflush\fR(8)
.PP
The Amanda Wiki:
: http://wiki.zmanda.com/
.SH "AUTHOR"
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
