'\" t
.\"     Title: amtape
.\"    Author: James da Silva <jds@amanda.org>
.\" Generator: DocBook XSL Stylesheets vsnapshot_8273 <http://docbook.sf.net/>
.\"      Date: 11/05/2009
.\"    Manual: System Administration Commands
.\"    Source: Amanda 2.6.1p2
.\"  Language: English
.\"
.TH "AMTAPE" "8" "11/05/2009" "Amanda 2\&.6\&.1p2" "System Administration Commands"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
amtape \- user interface to \fIAmanda\fR tape changer controls
.SH "SYNOPSIS"
.HP \w'\fBamtape\fR\ 'u
\fBamtape\fR \fIconfig\fR \fIcommand\fR [\fIcommand_options\fR...] [\fB\-o\ \fR\fIconfigoption\fR]...
.SH "DESCRIPTION"
.PP
\fBAmtape\fR
performs tape changer control operations\&. It uses the underlying tape changer script defined by the
\fBtpchanger\fR
option for a particular
\fIAmanda\fR
configuration as specified by the
\fIconfig\fR
argument\&.
.PP
Tape changers maintain a notion of the
\fIcurrent\fR
and
\fInext\fR
slot for each configuration\&. These may or may not correspond to an actual physical state of the device, but do tend to minimize searching through the tape storage slots\&. If the desired tape is in the current slot, it is likely the next tape needed is in the next slot rather than at some random position in the storage slots\&.
.PP
See the
\fBamanda\fR(8)
man page for more details about
\fIAmanda\fR\&.
.SH "COMMANDS"
.PP
\fBreset\fR
.RS 4
Reset the tape changer to a known state\&. The
\fIcurrent\fR
slot is set to the
\fIfirst\fR
slot\&. Other device\-specific side effects may occur\&. Some gravity stackers need to be reset to the top position by hand\&. This command notifies
\fIAmanda\fR
the stacker is back in that position\&.
.RE
.PP
\fBeject\fR
.RS 4
If a tape is loaded in the drive, it is ejected and returned to the slot from which it was loaded\&.
.RE
.PP
\fBclean\fR
.RS 4
If a cleaning tape is defined for the changer, it is used to clean the drive\&.
.RE
.PP
\fBshow\fR
.RS 4
Show the contents of all slots\&. This can be slow\&.
.RE
.PP
\fBlabel\fR \fIlabel\fR
.RS 4
Search for and load the
\fIAmanda\fR
tape with label
\fIlabel\fR\&.
.RE
.PP
\fBtaper\fR
.RS 4
Perform the
\fBtaper\fR
scan algorithm\&. Load the next tape in the configuration\'s tape sequence, or a fresh tape with a suitable label\&.
.RE
.PP
\fBdevice\fR
.RS 4
Display the name of the current tape device on
\fIstdout\fR\&.
.RE
.PP
\fBcurrent\fR
.RS 4
Display the current slot\&.
.RE
.PP
\fBupdate\fR
.RS 4
Update the changer label database, if it has one, to match the tapes now available\&.
.RE
.PP
\fBslot\fR \fIslot\fR
.RS 4
Eject any tape in the drive and put it away, then load the tape from slot
\fIslot\fR
and reset
\fIcurrent\fR\&.
.RE
.PP
\fBslot current\fR
.RS 4
Eject any tape in the drive and put it away, then load the tape from the current slot\&.
.RE
.PP
\fBslot next\fR
.RS 4
Eject any tape in the drive and put it away, then load the tape from the next slot and reset
\fIcurrent\fR\&.
.RE
.PP
\fBslot first\fR
.RS 4
Eject any tape in the drive and put it away, then load the tape from the first slot and reset
\fIcurrent\fR\&.
.RE
.PP
\fBslot advance\fR
.RS 4
Synonym for
\fBslot next\fR\&.
.RE
.PP
\fB\-o\fR \fIconfigoption\fR
.RS 4
See the "\fBCONFIGURATION OVERRIDE\fR" section in
\fBamanda\fR(8)\&.
.RE
.PP
This is useful with non\-gravity stackers to unload the last tape used and set up
\fIAmanda\fR
for the next run\&. If you just use
\fBeject\fR, the current tape will be mounted again in the next run, where it will be rejected as being still in use, ejected and the next tape requested\&. Using
\fBslot next\fR
followed by
\fBeject\fR
does an unnecessary mount\&.
.PP
Note: most changers optimize the
\fBslot\fR
commands to not eject the loaded tape if it is the one being requested\&.
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
: http://wiki.zmanda.com
.SH "AUTHORS"
.PP
\fBJames da Silva\fR <\&jds@amanda\&.org\&>
.PP
\fBStefan G\&. Weichinger\fR <\&sgw@amanda\&.org\&>
