.\"     Title: amverifyrun
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 02/07/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "AMVERIFYRUN" "8" "02/07/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
amverifyrun \- check the tapes written by the last Amanda run
.SH "SYNOPSIS"
.HP 12
\fBamverifyrun\fR \fIconfig\fR
.SH "DESCRIPTION"
.PP
\fBAmverifyrun\fR
read the log from the last
\fIAmanda\fR
run to find the slot of the first tape used and the number of tapes used. It call
\fBamverify\fR
with these argument.
.SH "SEE ALSO"
.PP
\fBamanda\fR(8),
\fBamverify\fR(8)
