# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.33
#
# Don't modify this file, modify the SWIG interface instead.

package Amanda::Tapefile;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package Amanda::Tapefilec;
bootstrap Amanda::Tapefile;
package Amanda::Tapefile;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package Amanda::Tapefile;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Amanda::Tapefile;

*read_tapelist = *Amanda::Tapefilec::read_tapelist;

# ------- VARIABLE STUBS --------

package Amanda::Tapefile;


@EXPORT_OK = ();
%EXPORT_TAGS = ();

=head1 NAME

Amanda::Tapefile - temporary hack

=head1 HACK?

Yeah, this is just here to make Amanda::Logfile usable.  This module
wil become Amanda::Tapelist in the next release.

=cut
1;
